### ISSUE TITLE
控制上传文件大小问题

### ISSUE THREAD

**Issue by simple7** [nanxiaobei/antd-img-crop#1]
裁剪之前没有暴露api，无法控制文件过大取消裁剪的操作

**Comment by nanxiaobei** [comment]
麻烦提供一个 demo，描述下需要实现的效果~

**Comment by nanxiaobei** [comment]
自 0.6.0 版本起，beforeUpload 检测移到了裁剪图片之前，可以先检测文件是否过大了。

**Comment by zhoujingsai** [comment]
> 自 0.6.0 版本起，beforeUpload 检测移到了裁剪图片之前，可以先检测文件是否过大了。

beforeUpload 检测前移，带来了新的问题：
大部分图片上传大小限制，只是想限制裁剪之后的大小，而不是裁剪之前的
如果想允许用户选择大尺寸图片，裁剪之后再判断所生成图片的大小是否符合要求，怎么实现呢？

建议：
新增一个 props 如 beforeOK，用来执行“裁剪之后、上传之前”的检测操作，在 onOK 中 this.resolve(newFile) 之前调用

如果需要，我可以提交pr

**Comment by nanxiaobei** [comment]
@zhoujingsai 
谢谢建议~
欢迎 PR。

经考虑，希望能将 `beforeUpload` 的检测时机还原为之前的情况，也就是裁剪后、上传前检测。
这是之前的代码：https://github.com/nanxiaobei/antd-img-crop/blob/d524530bac1adc367a53d880b65cee3466bc0a1b/src/index.jsx

然后为 ImgCrop 组件增加一个属性 `beforeCrop`，用于执行裁剪前的检测。

谢谢~
