### ISSUE TITLE
上传长图，进入无剪裁框

### ISSUE THREAD

**Issue by shaolunyedd01** [nanxiaobei/antd-img-crop#10]
在用你的组件，首先点个赞。在使用过程中，发现一些问题
1.上传长图，进入无剪裁框
2.点击模态框的时候已经取消裁剪了，但是点击确定按理是不更新图片的

**Comment by nanxiaobei** [comment]
你好，感谢反馈。
上述两个问题已在 1.1.0 版本中修复，请升级使用。

**Comment by shaolunyedd01** [comment]
bug已完美解决，感谢作者！好想给你打赏五块钱。。

**Comment by nanxiaobei** [comment]
哈哈，不用了，谢谢~
