### ISSUE TITLE
有一个建议，把组件改成hooks的形式扩展性会不会好点能

### ISSUE THREAD

**Issue by David2k13** [nanxiaobei/antd-img-crop#100]
现在在用的的你的的修改版，仔细看了一边代码，确实用了一些巧妙的办法去与antD的upload结合，我在想如果改成hooks的形式是不是可以和upload分离来获得更好的可拓展性呢，这只是个人的一点小建议

**Comment by nanxiaobei** [comment]
暂无此计划，欢迎 PR。
