### ISSUE TITLE
The image loses its transparency

### ISSUE THREAD

**Issue by kamilml** [nanxiaobei/antd-img-crop#105]
I was using the 3.3.0 version of this package. When I did update to the lastest version, the png or webp images loses its transparency.

Is there any new property to set or something? Or it is a bug?

Best regards.

**Comment by nanxiaobei** [comment]
There are no new features that affect this.

**Comment by Dricc** [comment]
Same for me, each cropped image loses his transparency, i change the `fillColor` params to `#fff0` to keep it
