### ISSUE TITLE
Img Crop optional

### ISSUE THREAD

**Issue by andrewfam** [nanxiaobei/antd-img-crop#108]
How do i make the image cropping optional where the cropping shows up only if the file uploaded is an image type?

**Comment by nanxiaobei** [comment]
try `beforeCrop` prop.

**Comment by andrewfam** [comment]
Hi, ok that works but when I try to upload a pdf or something, nothing happens when the modal does not open. Is there a method or something that will cause the upload to continue on?

**Comment by nanxiaobei** [comment]
try `Upload` `accept` prop.

https://ant.design/components/upload/#API

**Comment by andrewfam** [comment]
Sorry for not being clear. I have already set the accept prop to include the pdfs. But when i drag or add it in, nothing happens and the upload does not go through.

**Comment by andrewfam** [comment]
const beforeCrop = (file, fileList) => {
    return (file.type.indexOf('image') >= 0);
  }

const acceptList = ".pdf,'image/*'" 

  return (
    <AuthServiceLayout>
      <Row justify="space-between" align="middle" style={{ marginBottom: 20 }}>
        <Col>
          <Title level={2} style={{ marginBottom: 0 }}>
            All&nbsp;
            {pageItem}
          </Title>
        </Col>
        <Col>
          <Button type="primary" style={{ minWidth: 140 }} onClick={() => { modalRef.current.showModal(); }}>
            <PlusOutlined />
            &nbsp;Add Item
          </Button>
        </Col>
      </Row>
      <Card style={{ width: '100%' }}>
        <Row style={{ marginBottom: 40 }}>
          <Col span={4} />
          <Col span={16}>
            <ImgCrop beforeCrop={beforeCrop} rotate>
              <Dragger accept={acceptList} {...props}>
                <p className="ant-upload-drag-icon">
                  <InboxOutlined />
                </p>
                <p className="ant-upload-text">Click or drag file to this area to upload</p>
                <p className="ant-upload-hint">
                  Support for a single or bulk upload.
                </p>
              </Dragger>
            </ImgCrop>
          </Col>
          <Col span={4} />
        </Row>
        <Table columns={columns} dataSource={media} />
      </Card>
    </AuthServiceLayout>
  );
};

**Comment by nanxiaobei** [comment]
try `accept="image/*,.pdf"`
not `accept=".pdf,'image/*'"`

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Unique_file_type_specifiers
