### ISSUE TITLE
颜色设置有问题

### ISSUE THREAD

**Issue by andy136240860** [nanxiaobei/antd-img-crop#109]
用的ant design pro V5 , 更改了 primaryColor: '#F04F3D',  但是只要 cnpm 安装这个库之后， 大部分antd的组件都会变为默认的蓝色， 主题色设置失败

**Comment by nanxiaobei** [comment]
本库没有引入 antd 样式文件：
https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx

可能是别的地方设置有问题。
