### ISSUE TITLE
[Feature Request] Set height and width relative to image size

### ISSUE THREAD

**Issue by marcklingen** [nanxiaobei/antd-img-crop#11]
I really like the simplicity of antd-img-crop compared to other alternatives. I would like to set the initial dimensions relative to the image size the users uploaded. Is this already possible with antd-img-crop and I missed it or is is it maybe already on your feature roadmap?

**Comment by nanxiaobei** [comment]
Thank you for your support.
Actually in the beginning it was like what you expect, but after 1.0.0 it changed. Will support the "ratio" feature soon.

**Comment by marcklingen** [comment]
Tha js for the fast response. For our use case we would love to be able to set the ratio to 1:1 and by default the cropped area is as large as possible and centered on the other axis. To give some context we use antd-img-crop to let users crop their profile images and we would like them to crop them to a square but as little as possible to have a decent resolution.
Thanks for your work!

**Comment by nanxiaobei** [comment]
Hi, `antd-img-crop@2.0.0` has released.
Now you can just add `useRatio` prop to achieve what you want.

**Comment by marcklingen** [comment]
Hi @nanxiaobei,
thanks for adding the feature. I just updated to `2.0.0` and it works as expected.
Thank you very much!
