### ISSUE TITLE
不能按照指定宽高裁剪吗

### ISSUE THREAD

**Issue by HomyeeKing** [nanxiaobei/antd-img-crop#110]
现在放大图片之后，就会改变图片的尺寸，

**Comment by nanxiaobei** [comment]
无法指定宽高，只能使用比例。

**Comment by HomyeeKing** [comment]
@nanxiaobei  我看之前的示例是有的，  为什么不能指定裁剪区域大小，  图片裁剪会改变上传图片的尺寸， 如果需要同时裁剪和校验尺寸的话  不能指定裁剪区域固定大小的话  那就没法用了

**Comment by nanxiaobei** [comment]
目前使用是不支持固定数值得，因为又会有别的问题，
比如图片很大，而固定区域很小，在图片上就是一个小点。

**Comment by HomyeeKing** [comment]
@nanxiaobei  这算个极端的case吧  不算bug 算是使用者的问题 我个人认为加上比较好
