### ISSUE TITLE
Maximum size of a <canvas> element.

### ISSUE THREAD

**Issue by OleksandrAntonenko1** [nanxiaobei/antd-img-crop#114]
Hey, I have found out that this component is running poorly on ios mobile devices. Due to the max size of the canvas which is 16777216. 

## Steps to reproduce
This behaviour is can be reproduced with an example on the [and page](https://ant.design/components/upload/) and ios driven device. Just upload an image which area is bigger than  16777216px.
![image](https://user-images.githubusercontent.com/42577309/104610213-88796780-568c-11eb-8c86-b76b60ff05cb.png)
## What is actually happening?
As a result, you will get a black image and a warning.
![image](https://user-images.githubusercontent.com/42577309/104610287-9cbd6480-568c-11eb-80ac-cc47152688cc.png)
![image](https://user-images.githubusercontent.com/42577309/104610440-cd050300-568c-11eb-92d7-bf4b3e41b8ae.png)

**Comment by nanxiaobei** [comment]
Hi, since Ant Design is mainly used for desktop, so this  component will not be specially optimized for mobile devices.

**Comment by fullstackctp** [comment]
Is there any way to get around this issue in ios mobile devices because I have to change or use different library for cropping images in ios devices.
Any help will be useful.
