### ISSUE TITLE
Crop area too small

### ISSUE THREAD

**Issue by pedrozocatelli** [nanxiaobei/antd-img-crop#115]
I'm using Firefox and antd-img-crop@3.13.2

Whenever I try to upload a picture, the size of the crop area is too small, smaller even than the image itself.

![image](https://user-images.githubusercontent.com/22919569/104728921-64626880-5716-11eb-910d-f627976ad667.png)

![image](https://user-images.githubusercontent.com/22919569/104728949-73491b00-5716-11eb-9b56-bd14a3fd5c69.png)

```
  onChange = ({ fileList: newFileList }) => {
    this.setState({ avatar: newFileList });
  };


  onPreview = async (file) => {
    let src = file.url;
    if (!src) {
      src = await new Promise((resolve) => {
        const reader = new FileReader();
        reader.readAsDataURL(file.originFileObj);
        reader.onload = () => resolve(reader.result);
      });
    }
    const image = new Image();
    image.src = src;
    const imgWindow = window.open(src);
    imgWindow.document.write(image.outerHTML);
  };

  dummyRequest = ({ file, onSuccess }) => {
    setTimeout(() => {
      onSuccess('ok');
    }, 0);
  };


 <ImgCrop rotate>
        <Upload
          customRequest={this.dummyRequest}
          listType="picture-card"
          fileList={avatar}
          onChange={this.onChange}
          onPreview={this.onPreview}
          maxCount={1}
        >
              {avatar.length === 0 && <FaFileUpload size={25} />}
        </Upload>
</ImgCrop>
```

**Comment by nanxiaobei** [comment]
I  don't get your point. from the pictures, there's no problem.

**Comment by pedrozocatelli** [comment]
If the user don't want to crop any part of the image, there's no way to do that, in some cases, I would like a way so that the crop area can fit the entire original picture and let user chose whether they want to crop it or not.

![image](https://user-images.githubusercontent.com/22919569/104737739-67178a80-5723-11eb-9193-10ac73c50167.png)

![image](https://user-images.githubusercontent.com/22919569/104737806-80203b80-5723-11eb-8959-b0ff00563278.png)

Something like this, basically, increase the default crop area to the width and height of the picture and the them zoom in if they want to crop something.

**Comment by nanxiaobei** [comment]
You can use `minZoom` crop to resize the whole image inside crop area.

Currently there is no way to `increase the default crop area to the width and height of the picture`, It's a bit of a hassle.

PR welcome.
