### ISSUE TITLE
Modal opens behind existing modal 

### ISSUE THREAD

**Issue by msagerup** [nanxiaobei/antd-img-crop#116]
Hi, 

I am opening this in an exisitng modal that is allready open. 
The problem is that ImageCrop opens behind the modal that is allready open. 

Is there a way to access the z-Index of the ImageCrop modal ?

**Comment by nanxiaobei** [comment]
you can set it yourself using `.antd-img-crop-modal` class.

**Comment by msagerup** [comment]
how do i do that ? Do i need to change it in the node modules ? 

![image](https://user-images.githubusercontent.com/23620566/110687034-5a258d80-81e0-11eb-9c7f-c4e2e8166e79.png)
 here ?

**Comment by msagerup** [comment]
sorry, im stupid . 

like this. Got it. 

thanks

![image](https://user-images.githubusercontent.com/23620566/110689494-08323700-81e3-11eb-89de-5d87ebfb4c11.png)
