### ISSUE TITLE
png图片被裁剪后体积反而变大了

### ISSUE THREAD

**Issue by junoAGG** [nanxiaobei/antd-img-crop#12]
png图片被裁剪后体积反而变大了，貌似是改变的图片的位深度这个属性，请问怎么控制这个值不变呢

**Comment by nanxiaobei** [comment]
你好，`antd-img-crop` 未对图片体积做特殊处理，可自行通过 [`lrz`](https://github.com/think2011/localResizeIMG) 在 `beforeUpload` 中压缩图片

**Comment by wufu-fire** [comment]
antd-img-crop剪裁以后，图片变大了。看了源码，应该是canvas导出图片的时候导致的。

**Comment by nanxiaobei** [comment]
可自行在 Upload 的 `beforeUpload` 中处理图片压缩。
