### ISSUE TITLE
Can't resolve '@babel/runtime/helpers/esm/asyncToGenerator'

### ISSUE THREAD

**Issue by Pasoul** [nanxiaobei/antd-img-crop#122]
## 问题
安装`antd-img-crop`后，运行项目报错
```
./node_modules/antd-img-crop/dist/antd-img-crop.esm.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/asyncToGenerator' in '/Users/admin/Desktop/panda/web-ac-cms/node_modules/antd-img-crop/dist'
```
但是node_modules存在该文件，为什么会报错找不到呢？
![image](https://user-images.githubusercontent.com/22902187/111022381-63477200-840d-11eb-9d24-788a16bef01f.png)

版本号：
 "@babel/runtime": "^7.13.10"
"antd-img-crop": "^3.14.1"

**Comment by nanxiaobei** [comment]
可尝试删除 `node_modules` 目录重启 `npm install` 一下。

如果还不行的话，可以提供一个 demo。

**Comment by Pasoul** [comment]
先close吧，有空试试
