### ISSUE TITLE
Unable to crop image and disable uploading by returning "false" from "beforeUpload"

### ISSUE THREAD

**Issue by GVanderLugt** [nanxiaobei/antd-img-crop#123]
I am using the `Upload` component as a local file input and am not using it to actually upload my files. I need to handle the file uploads myself. I am doing this by returning `false` from `beforeUpload`. However, if I do this while using `antd-img-crop`, the cropping functionality does not work.

This is my code:

```
...

const ImageInput: React.FC<ImageInputProps> = ({ maxCount, onChange }) => {
  const handleChange = { ... };
  const handleRemove = { ... };
  const handlePreview = { ... };
  
  const beforeUpload = () => {
    return false;
  };

  return (
    <ImgCrop grid rotate>
      <Upload
        accept='image/png, image/jpeg'
        listType='picture-card'
        onChange={handleChange}
        onRemove={handleRemove}
        onPreview={handlePreview}
        maxCount={maxCount}
        beforeUpload={beforeUpload}
      >
        <div>
          <Text type='secondary'>
            <PlusOutlined />
          </Text>
          <div style={{ marginTop: 8 }}>
            <Text type='secondary'>Upload Image</Text>
          </div>
        </div>
      </Upload>
    </ImgCrop>
  );
};

export default ImageInput;
```

The cropping only works if I remove `beforeUpload={beforeUpload}`. I've tried returning a lot of different things from `beforeUpload`, and nothing has worked.

Any ideas? Any help would be greatly appreciated. I took a look a the source code and I think the issue is that on [this line](https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L281) it is just rejecting. The `newFile` at this point is just being lost. I'm not sure what to do about it, though.

**Comment by nanxiaobei** [comment]
You can get the `newFile` by the first argument of your `beforeUpload`,  and handle it yourself.

https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L273

**Comment by GVanderLugt** [comment]
@nanxiaobei So as an example, in `beforeUpload` I could set the `file` or `fileList` to the local component state and then pass that to the `Upload` `fileList` property? And then return `false` from `beforeUpload` to prevent the `XMLHttpRequest`?

**Comment by nanxiaobei** [comment]
> @nanxiaobei So as an example, in `beforeUpload` I could set the `file` or `fileList` to the local component state and then pass that to the `Upload` `fileList` property? And then return `false` from `beforeUpload` to prevent the `XMLHttpRequest`?

You can not pass the `file` from `beforeUpload` directly to the `fileList` prop.

Because the `fileList` item needs an `UploadFile` object.

https://ant.design/components/upload/#UploadFile

**Comment by nanxiaobei** [comment]
> @nanxiaobei So as an example, in `beforeUpload` I could set the `file` or `fileList` to the local component state and then pass that to the `Upload` `fileList` property? And then return `false` from `beforeUpload` to prevent the `XMLHttpRequest`?

You can write `beforeUpload` in this way:

```js
const [fileList, setFileList] = useState([]);

const beforeUpload = (file) => {
  const reader = new FileReader();
  reader.readAsDataURL(file);
  reader.onload = () => {
    setFileList((prev) => [...prev, { url: reader.result }]);
  };

  // then upload `file` from the argument manually
  return false;
};
```

and remove `onChange={onChange}` to update `fileList` manually.

**Comment by GVanderLugt** [comment]
Thank you so much for your help, I will give this a shot!

**Comment by GVanderLugt** [comment]
This worked, thanks again!

**Comment by MasonHM** [comment]
> https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L273

For future users where the repo changed under the link, here is the correct line: https://github.com/nanxiaobei/antd-img-crop/blob/bc62dfc24672649b52d192499ad2e469ffbf80d3/src/index.jsx#L273

**Comment by samyarkd** [comment]
There is a problem with this solution. The property called `originFileObj` will be undefined. 
How can we achieve it because the `url` is base64.
Also, it's not type safe and i get many type errors.

> > @nanxiaobei So as an example, in `beforeUpload` I could set the `file` or `fileList` to the local component state and then pass that to the `Upload` `fileList` property? And then return `false` from `beforeUpload` to prevent the `XMLHttpRequest`?
> 
> You can write `beforeUpload` in this way:
> 
> ```js
> const [fileList, setFileList] = useState([]);
> 
> const beforeUpload = (file) => {
>   const reader = new FileReader();
>   reader.readAsDataURL(file);
>   reader.onload = () => {
>     setFileList((prev) => [...prev, { url: reader.result }]);
>   };
> 
>   // then upload `file` from the argument manually
>   return false;
> };
> ```
> 
> and remove `onChange={onChange}` to update `fileList` manually.

**Comment by renellc** [comment]
Hey all, for anyone reading in the future:

If you are using this approach with `react-hook-form` and you're doing something like this:

```
<Controller
  control={control}
  name="myField"
  render={({ field }) => (
    <ImgCrop>
      <Upload beforeUpload={...}>
        ...
      </Upload>
    </ImgCrop>
  )} 
/>
```

you'll have to use the `field.onChange` function and pass whatever you store into your field there. When you call `FileReader.readAsDataURL`, you might encounter the error `url.split() is not a function` or `url.split() is undefined`. To fix this, for some reason I had to give `onChange` a no-op function (`onChange={() => {}}`) for it to not cause this error.

I can't currently look into why this behavior exists and how to fix it (if it is indeed a bug), but I'm leaving this comment for any future readers to stumble upon.
