### ISSUE TITLE
Size increased after upload image, but i didn't crop or rotate it

### ISSUE THREAD

**Issue by fung-leung** [nanxiaobei/antd-img-crop#125]
version 3.14.1

I upload a 4k images, 5.5mb

after upload, it become 13.6mb

I am using code below:

              <ImgCrop aspect={1} quality={1} rotate>
                <Upload
                  name="file"
                  accept=".jpg,.png,.jpeg"
                  listType="picture-card"
                  className="avatar-uploader"
                  showUploadList={false}
                  directory={false}
                  multiple={false}
                  beforeUpload={beforeUpload}
                  customRequest={({ file, onError }) => {
                    setLogoLoading(true);
                    mediaUpload(mediaDir.eventPic, file as RcFile)
                      .then(handleUploadSuccess)
                      .catch(onError);
                  }}
                >
                  {logoUrl ? (
                    <img src={logoUrl} alt="pic" style={{ width: '100%' }} />
                  ) : (
                    logoUploadButton
                  )}
                </Upload>
              </ImgCrop>

**Comment by fung-leung** [comment]
FYI, I didn't crop or rotate it. Here is the source image.


![source](https://user-images.githubusercontent.com/49734148/112587177-12d20a80-8e38-11eb-8bb9-e524d44439e5.jpg)

**Comment by nanxiaobei** [comment]
Yes, it's a predictable change.

You can try reducing the `quality` prop to find the right size.
