### ISSUE TITLE
NS_ERROR_FAILURE on large images (10MB)

### ISSUE THREAD

**Issue by ds1371dani** [nanxiaobei/antd-img-crop#126]
if image size is too big (10MB) this error occurs:
```
[Exception... "Failure"
nsresult: "0x80004005 (NS_ERROR_FAILURE)"
location: "JS frame :: https://4qoom5p9x4.csb.app/node_modules/antd-img-crop/dist/antd-img-crop.esm.js :: _callee2$ :: line 207"
data: no]
```

I tried this image: [https://wallpaperaccess.com/download/10k-resolution-651192](https://wallpaperaccess.com/download/10k-resolution-651192)

**Comment by nanxiaobei** [comment]
Because the image is too large, the error was reported when processing canvas by the system.

https://stackoverflow.com/questions/12642222/canvascontext-fillrect-throws-ns-error-failure-exception-in-firefox
