### ISSUE TITLE
antd->upload组件自己处理上传文件和antd-img-crop的代码有冲突

### ISSUE THREAD

**Issue by MemoryNoodles** [nanxiaobei/antd-img-crop#127]
需求：upload组件beforeUpload函数 return false; 在onChange函数中自己处理上传逻辑。
 antd-img-crop库会认为我没有上传代码如下
if (res === false) return rejectRef.current('not upload');

**Comment by nanxiaobei** [comment]
`beforeUpload` 的处置行为和 `antd` 官方文档一致：https://ant.design/components/upload-cn/#API

**Comment by MemoryNoodles** [comment]
> `beforeUpload` 的处置行为和 `antd` 官方文档一致：https://ant.design/components/upload-cn/#API

beforeUpload，如果不return false,  upload组件会自己处理上传逻辑并标记状态。状态为done时我才能手动调用阿里云的OSS.multipartUpload上传。这时要等upload上传逻辑完了才会走我自己的上传。这就等于有两个上传了
