### ISSUE TITLE
`beforeUpload` 的处置行为和 `antd` 官方文档一致：https://ant.design/components/upload-cn/#API

### ISSUE THREAD

**Issue by MemoryNoodles** [nanxiaobei/antd-img-crop#128]
`beforeUpload` 的处置行为和 `antd` 官方文档一致：https://ant.design/components/upload-cn/#API

_Originally posted by @nanxiaobei in https://github.com/nanxiaobei/antd-img-crop/issues/127#issuecomment-817171018_

beforeUpload，如果不return false, upload组件会自己处理上传逻辑并标记状态。状态为done时我才能手动调用阿里云的OSS.multipartUpload上传。这时要等upload上传逻辑完了才会走我自己的上传。这就等于有两个上传了

**Comment by MemoryNoodles** [comment]
![image](https://user-images.githubusercontent.com/19926700/114291748-69884700-9abc-11eb-8bb4-1e5aad1b41eb.png)

**Comment by nanxiaobei** [comment]
没太懂你的问题所在，

在 `beforeUpload` 中 `return false` 与 `antd-img-crop` 源码中的 `reject()` 都是阻止上传，

两者是 `beforeUpload` 的两种使用方式，一种同步一种异步，所以说处置行为是一致的。

只不过在 `antd-img-crop` 中对 `beforeUpload` 进行了包装，所以使用的是 Promise 的形式。

**Comment by MemoryNoodles** [comment]
> 没太懂你的问题所在，
> 
> 在 `beforeUpload` 中 `return false` 与 `Promise.reject()`（ `antd-img-crop` 源码中）都是阻止上传，
> 
> 两者是 `beforeUpload` 的两种使用方式，一种同步一种异步，所以说处置行为是一致的。
> 
> 只不过在 `antd-img-crop` 中对 `beforeUpload` 进行了包装，所以使用的是 `Promise.reject()` 的形式。

我看源码上是如果你所说的，但是upload在被antd-img-crop包裹了一层beforeUpload中return false后，就不再触发onchange了

**Comment by MemoryNoodles** [comment]
解决方案
如果beforeUpload函数return false; 说明可能用户需要自己处理上传逻辑。那这个时候需要手动调用upload的onChange事件

 const { beforeUpload, accept,onChange, ...restUploadProps  } = upload.props;
    beforeUploadRef.current = beforeUpload;


if (res === false) {
          onChangeRef.current({file:newFile})
          return rejectRef.current('not upload');
        }

**Comment by nanxiaobei** [comment]
这里的 `beforeUploadRef.current` 就是你自己的 `beforeUpload`，可以在这里拿到 `newFile`。

https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L273

**Comment by MemoryNoodles** [comment]
> 这里的 `beforeUploadRef.current` 就是你自己的 `beforeUpload`，可以在这里拿到 `newFile`。
> 
> https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L273

我当然知道，前提是beforeUpload不返回return false； 只是这样返回的文件就带有status状态了。我需要的是不带有状态的file文件
