### ISSUE TITLE
antd 修改默认前缀之后， 不能显示对应的弹窗。

### ISSUE THREAD

**Issue by minjie946** [nanxiaobei/antd-img-crop#131]
![image](https://user-images.githubusercontent.com/26477709/115849879-e7066c80-a457-11eb-83d4-78b0e4e60718.png)
![image](https://user-images.githubusercontent.com/26477709/115849924-f38ac500-a457-11eb-991d-abda92f41e70.png)

**Comment by nanxiaobei** [comment]
因为 `antd-img-crop` 用到的 `Modal` 组件是写在自身代码中。因此，可能未被外部项目配置所影响。

暂无法支持外部项目配置的变化，可自行将 `antd-img-crop` 源代码复制到项目中，然后改变 `Modal` 与 `Slider` 引入路径使用：

https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L5-L6
