### ISSUE TITLE
A canvas exceeds error occurred when trying to upload a photo token by camera on iphoneX

### ISSUE THREAD

**Issue by CODEOrz** [nanxiaobei/antd-img-crop#133]
使用该组件+antd upload上传由iPhoneX相机拍摄的照片时，会提示canvas超限报错
- Canvas area exceeds the maximum limit (width * height > 16777216).

当上传手机截图时，无此报错。

**Comment by nanxiaobei** [comment]
据查询，应该是 iOS 系统有限制。因为截取图片时会使用 canvas 重新绘制截取部分。

https://github.com/fabricjs/fabric.js/issues/4945
https://github.com/openlayers/openlayers/issues/9166

**Comment by CODEOrz** [comment]
> 据查询，应该是 iOS 系统有限制。因为截取图片时会使用 canvas 重新绘制截取部分。
> 
> [fabricjs/fabric.js#4945](https://github.com/fabricjs/fabric.js/issues/4945)
> [openlayers/openlayers#9166](https://github.com/openlayers/openlayers/issues/9166)

是的，我把 canvas初始化时的maxLength 可取的最大值做了一个限制就好了

**Comment by Joshuajrodrigues** [comment]
Did you manage to fix this ? Im currently having an issue where it just reloads thr page
