### ISSUE TITLE
Preview after cropping is blacked out on mobile

### ISSUE THREAD

**Issue by jzzfs** [nanxiaobei/antd-img-crop#135]
**Issue**
Both of these two processes end up with a blacked-out preview:
1. Click upload -> **take an image** -> crop it -> click OK
2. Click upload -> **use an existing image** -> crop it -> click OK

**Reproducible on https://codesandbox.io/s/antd-img-crop-4qoom5p9x4 on any mobile browser** -- I've tested
- safari iPhone 11 (`Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1`)
- chrome on Xiaomi Android (`Mozilla/5.0 (Linux; Android 9; Mi A1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.210 Mobile Safari/537.36`)

**Video:**
![ezgif-2-65b77e07c879](https://user-images.githubusercontent.com/9054705/119348841-b22b4680-bc9d-11eb-9d9a-2a5abc96021a.gif)

**Screenshot:**
![IMG_17AFB6C82016-1](https://user-images.githubusercontent.com/9054705/119348502-3f21d000-bc9d-11eb-8a03-4fece60c96ac.jpeg)

**Comment by nanxiaobei** [comment]
`imgWindow.document` error is in the demo code: https://codesandbox.io/s/antd-img-crop-4qoom5p9x4

And demo code updated.

**Comment by jzzfs** [comment]
Thanks. The sandbox err must've been a coincidence but the mobile error still persists -- I'm unable to neither upload saved pictures nor freshly taken ones.
Mind you, the cropper is able to render the canvas but the "OK" click results in a blacked out image. Can you check on your phone?

**Comment by jzzfs** [comment]
I've cloned the module and everything works fine until the canvas modifications begin.

In other words, if I _skip_ the canvas manipulations (zoom/move/rotate) and resolve the [`naturalImg.src`](https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L231) and _don't_ export the canvas to the file, the `naturalImage` b64 source renders correctly.

The problem cannot be the canvas -> blob -> file conversion because if I resolve `canvas.toDataURL('image/jpeg')`, it results in an already "corrupted" data url...

This makes me think it may be some mobile canvas manipulation inconsistency?

**Comment by nanxiaobei** [comment]
There are some issues about it before: 

https://github.com/nanxiaobei/antd-img-crop/issues/30
https://github.com/nanxiaobei/antd-img-crop/issues/55

PR has been added before, but I don't know why there are still problems.
At present, I have no time to solve this problem, sorry.

**Comment by jzzfs** [comment]
OK, thanks for the heads-up.

**Comment by jzzfs** [comment]
For those that stumble on this in the future -- it turns out, canvas dimension vary across devices. The best bet it to downsize/compress the image before passing it to the cropper. More on this [in this thread](https://github.com/ricardo-ch/react-easy-crop/issues/91#issuecomment-766167263).
