### ISSUE TITLE
I need to CropSize of width:275 and height:130 , i already used cropperProps and cropSize props, but cropSize can be modified only by aspect props but i need to use width and height in setting the cropSize.

### ISSUE THREAD

**Issue by arunkumaranke-kaaylabs** [nanxiaobei/antd-img-crop#136]
i already used cropperProps and cropSize props, but cropSize can be modified only by aspect props but i need to use width and height in setting the cropSize

**Comment by nanxiaobei** [comment]
Sorry, only supports ratio, real width and height are not supported.
