### ISSUE TITLE
第一次图片裁剪时的问题

### ISSUE THREAD

**Issue by BeADre** [nanxiaobei/antd-img-crop#14]
第一次裁剪图片时  若直接移动裁剪部分或直接拉大裁剪边框  裁剪边框会弹到右下角或直接消失

**Comment by nanxiaobei** [comment]
你好，我这里没有发现类似情况，请提供一个可复现的 Demo

**Comment by BeADre** [comment]
> 你好，我这里没有发现类似情况，请提供一个可复现的Demo
我该咋给你demo呢？？   我就是直接安装了一个create-react-app，然后把你沙盒中的那个例子代码复制过来的  安装好依赖后就有问题。然后我昨天看了下源码  是你依赖的react-image-crop这个包导致的问题，在228行，调用convertToPixelCrop函数后因为unit为undefined,所以返回的对象中x和y被改了

**Comment by nanxiaobei** [comment]
感谢反馈，已升级组件到 `2.0.1` 修复了此问题
