### ISSUE TITLE
在typeScript中使用oss上传，配合此组件失败

### ISSUE THREAD

**Issue by Sunnyjson** [nanxiaobei/antd-img-crop#142]
1.  使用ant官方推荐的oss上传 [OSS上传](https://ant.design/components/upload-cn/#components-upload-demo-upload-with-aliyun-oss) 
2. 在beforeUpload函数内增加的url，getExtraData获取的file对象没有返回url， 去掉ImgCrop正常使用

**Comment by nanxiaobei** [comment]
可尝试将此例 [https://ant.design/components/upload-cn/#components-upload-demo-upload-with-aliyun-oss](https://ant.design/components/upload-cn/#components-upload-demo-upload-with-aliyun-oss) `beforeUpload` 中获取的 file 数据手动设置给 Upload 组件的 `data` 属性
