### ISSUE TITLE
Error using imgCrop on oss upload

### ISSUE THREAD

**Issue by Sunnyjson** [nanxiaobei/antd-img-crop#143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-urvf3?file=/index.js)

### Steps to reproduce
1. using imgCrop
2. data callback => file not has url

### What is expected?
has url

### What is actually happening?
not has url

| Environment | Info |
|---|---|
| antd | 4.15.1 |
| React | 17.x |
| System | mac |
| Browser | chrome |

**Comment by Sunnyjson** [comment]
把antd 降到4.6.1, antd-img-crop 降到3.9.0 解决了这个问题， 应该是在之后的版本出现了这个bug， 希望能得到解决

**Comment by Sunnyjson** [comment]
目前通过降版本来解决了这个问题， 在ant-design 提了issues https://github.com/ant-design/ant-design/issues/30988 ，未能得到解决

**Comment by nanxiaobei** [comment]
之前 `antd` Upload 的 `data` 属性不支持函数形式，函数形式应该是后来加的，所以不兼容。

建议直接给 data 赋值，不使用函数属性。

**Comment by Sunnyjson** [comment]
直接给data赋值， upload上传是失败的 这不是一个解决方法 @nanxiaobei
