### ISSUE TITLE
antd设置prefixCls后，该组件的外层modal没有设置prefixCls，导致没有样式

### ISSUE THREAD

**Issue by wuyuehui** [nanxiaobei/antd-img-crop#144]
- 使用该组件外层modal没有prefixCls

![image](https://user-images.githubusercontent.com/37658373/122374251-ca3c7000-cf94-11eb-9a86-977431e04a49.png)

- 直接用antd的modal有prefixCls

![image](https://user-images.githubusercontent.com/37658373/122374227-c4df2580-cf94-11eb-8009-032e8430fd94.png)

**Comment by nanxiaobei** [comment]
此组件不属于 `antd` 自有组件，所以无效。

建议将 `antd-img-crop` 代码拷贝到项目中使用。
