### ISSUE TITLE
裁剪后图片大小不符合预期

### ISSUE THREAD

**Issue by zj1024** [nanxiaobei/antd-img-crop#147]
使用canvas截屏形式 + quality会导致图片的内存增大，有更好的方案吗？

目前测试40k图，裁剪后增加到160k

就会造成一个问题，产品上限制2m图，用户上传了1m图，裁剪后超过2m导致触发过大校验。

**Comment by nanxiaobei** [comment]
可使用 Promise 形式 `beforeUpload`，自行处理图片

```jsx
<Upload 
  beforeUpload={(file) => {
    return new Promise((resolve) => {
      const minifiedFile = compressFile(file); // 压缩图片
      resolve(minifiedFile);
    })
  }}
/>
```

https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L288-L291
