### ISSUE TITLE
Error using antd-img-crop with FormItem in antd

### ISSUE THREAD

**Issue by WilferCiro** [nanxiaobei/antd-img-crop#148]
When I use antd-img-crop with Form.Item, the value doesn't updates when I obtain it from form.getFieldsValue(); and other issues.

I created an example solving this, I like that you use this in the examples.

https://codesandbox.io/s/customized-form-controls-antd4168-forked-cnwfk?file=/index.js

I hope it is useful

**Comment by nanxiaobei** [comment]
`antd-img-crop` is not a `antd` form field component, you need to customize it. https://ant.design/components/form/#components-form-demo-customized-form-controls

**Comment by hosseini44444** [comment]
The solution is building a custom component like this which behaves exactly like `Upload` but with crop feature
