### ISSUE TITLE
Image crop not working in ios mobile devices.

### ISSUE THREAD

**Issue by fullstackctp** [nanxiaobei/antd-img-crop#152]
I am seeing this error which is also previously seen and reported.
some links which discusses the same issue.
https://githubmemory.com/repo/nanxiaobei/antd-img-crop/issues/114
https://githubmemory.com/repo/nanxiaobei/antd-img-crop/issues/135

The image crop is not working on ios devices and it is also mentioned by you that antd-img-crop is mainly used for desktop, and not optimised for mobile devices.
This makes it harder to use the same library across your website since in mobile devices it won't work(ios only I don't see this problem on android). Is there any workaround for this issue or we have to use different library for ios devices.

**Comment by nanxiaobei** [comment]
Sorry, no plan for it now, and PR welcome.
