### ISSUE TITLE
Modal的onCancel和onOk事件不准备开放出来吗

### ISSUE THREAD

**Issue by powerXuDong** [nanxiaobei/antd-img-crop#153]
有时候需要在弹出和取消剪切的modal的时间点上做一些事情；目前只能通过beforeCrop来监听到modal的弹出   取消事件不能监听到

**Comment by nanxiaobei** [comment]
暂无计划

**Comment by nanxiaobei** [comment]
`3.16.0` 已添加 `onModalOk` 与 `onModalCancel` 回调。

https://github.com/nanxiaobei/antd-img-crop#props
