### ISSUE TITLE
长图截出来是黑的

### ISSUE THREAD

**Issue by mqliutie** [nanxiaobei/antd-img-crop#154]
目前场景是上传头像,  模拟网络故障或服务端接口返回报错,  此时弹层默认都会关闭,  如果保留弹层, 给用户继续尝试体验会更好一点, 不知道支不支持

**Comment by nanxiaobei** [comment]
感谢反馈，长图问题 `3.16.0` 已修复。

同时添加了 `onModalOk` 与 `onModalCancel` 回调：https://github.com/nanxiaobei/antd-img-crop#props
