### ISSUE TITLE
I can't drag when the imagen is smaller than square

### ISSUE THREAD

**Issue by kamilml** [nanxiaobei/antd-img-crop#158]
Hello sir,

I have this problem, I can drag normally when the image is bigger than square, but I can't when is not

![](https://i.imgur.com/xdBD3NY.png)

**Comment by nanxiaobei** [comment]
Please provide a reproducible demo.

**Comment by nanxiaobei** [comment]
OK, I see.

Yes, you really can't drag when zoom < 1.

It's not support by [`react-easy-crop`](https://github.com/ricardo-ch/react-easy-crop), which is used for `antd-img-crop`.

**Comment by kamilml** [comment]
I found the solution, I am sorry for disturb :P

```javascript
cropperProps={{
    restrictPosition: false
}}
```
