### ISSUE TITLE
width error in the controls

### ISSUE THREAD

**Issue by kamilml** [nanxiaobei/antd-img-crop#160]
Hello sir,

As you can see in this image, the width of the controls div are failing

![](https://i.imgur.com/0s50BW9.png)

![](https://i.imgur.com/2XuYjCX.png)

I am using:
```json
    "dependencies": {
        "@reduxjs/toolkit": "^1.6.2",
        "antd": "^4.16.13",
        "antd-img-crop": "^3.16.0",
        "next": "^11.1.2",
        "next-redux-wrapper": "^7.0.5",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "react-redux": "^7.2.5"
    },
```

**Comment by nanxiaobei** [comment]
Maybe forgot `import 'antd/es/slider/style'`?

**Comment by kamilml** [comment]
I think the problem is I am using variable css config, with my own `prefixCls`.

My html code looks like this (with `dark-` prefix)
![](https://i.imgur.com/0K1pYMq.png)

How can I solve this?

**Comment by nanxiaobei** [comment]
Copy `antd/es/slider/style` to another file, add  it to project, change `.@{slider-prefix-cls}` to `.ant-slider`.
