### ISSUE TITLE
prop-types is a peer dependencies not a dev dependency

### ISSUE THREAD

**Issue by damiangreen** [nanxiaobei/antd-img-crop#165]
This forces yarn 3 users to have to add `packageExtensions`  overrides for this library

**Comment by nanxiaobei** [comment]
It is peer?

https://github.com/nanxiaobei/antd-img-crop/blob/main/package.json#L32

**Comment by damiangreen** [comment]
yes

**Comment by damiangreen** [comment]
I think you may have misunderstood. 
it is meant to be a dev dependency,
currently it is a poer dependency
Shall i raise a PR?

**Comment by nanxiaobei** [comment]
It's in the source code, so it's not a dev dependency.

And I will remove `prop-types` in the next version.
