### ISSUE TITLE
Crop location problem when rotate

### ISSUE THREAD

**Issue by lfirek** [nanxiaobei/antd-img-crop#169]
Hello,

I found bug in latest version of antd-img-crop. When you start rotating and crop, cropped area is outside the grid. It's easy to reproduce on example. I'm using MacBook + Chrome.

![Zrzut ekranu 2022-01-14 o 09 56 49](https://user-images.githubusercontent.com/5695400/149498489-4f120197-1a4d-4fa4-ab82-c39b85edcb63.png)
![Zrzut ekranu 2022-01-14 o 09 57 05](https://user-images.githubusercontent.com/5695400/149498483-073b5cc8-6607-4382-90a3-edcd320532dc.png)

**Comment by nanxiaobei** [comment]
Thanks for your feedback.

Fixed in `4.1.0`.
