### ISSUE TITLE
Feature request for get unique className or id for Modal.

### ISSUE THREAD

**Issue by lfirek** [nanxiaobei/antd-img-crop#170]
Hello,

I write with feature request for get unique className or id for Modal. It's really easy to create Ant Img Crop but when I want to customize crop area grid with other colors and background it's works only for one global class. In our project we have few areas with other conent and we want to customize grid area for each of them. At this moment it's impossible because className is created with constat variable `cls`. 

It's possible to add some extra variable for className of Modal?

**Comment by nanxiaobei** [comment]
You can use `.img-crop-modal { }`.

**Comment by lfirek** [comment]
@nanxiaobei yea, but this is not unique. If in application I use two different img crop and I need to create style for each. It's impossible to create 2 unique styles for each img crop.

**Comment by nanxiaobei** [comment]
Understood, will add `className` later.
