### ISSUE TITLE
无法自定义cropSize

### ISSUE THREAD

**Issue by 13164286167** [nanxiaobei/antd-img-crop#171]
跪求大佬急速支持。
源码中按照比例计算cropSize会覆盖cropperProps中传入的cropSize，导致无法传入指定大小的cropSize。
请求增加参数，或使cropSize不会覆盖cropperProps的cropSize。

**Comment by 13164286167** [comment]
我看了下历史版本，2.x 版本是支持的，现在为啥不支持了呀，出于什么考虑呢，那现在要处理固定宽高的截取应该怎么处理

**Comment by nanxiaobei** [comment]
cropSize 是用于源码中的，用于解决之前遇到的问题。
支持的话改动太大，也可能引发历史问题，目前没有这个打算。
