### ISSUE TITLE
能开放所有其他的antd-modal传参吗

### ISSUE THREAD

**Issue by u373693041** [nanxiaobei/antd-img-crop#174]

**Comment by u373693041** [comment]
![image](https://user-images.githubusercontent.com/48196776/151501381-50c32e36-b526-4f8f-b39c-f43dd24b1f28.png)
![image](https://user-images.githubusercontent.com/48196776/151501440-c0ba4034-f931-45da-a9cf-d2f2dc7620f9.png)
能麻烦这里或在哪里改下，支持下所有的antd-modal的参数可以吗

**Comment by nanxiaobei** [comment]
暂无此计划。
