### ISSUE TITLE
safari上，裁剪框，有时候出不来

### ISSUE THREAD

**Issue by lovelyyl** [nanxiaobei/antd-img-crop#177]
![image](https://user-images.githubusercontent.com/45654799/153986188-5a0b6328-41f5-4d91-a850-607b9e51c648.png)

onMediaLoaded这个函数，拿到的宽高都是0。

目测，是因为Modal还没渲染好，导致， react-easy-crop 这个组件渲染的时候，拿到的宽高也是0

**Comment by bijiasuo2006** [comment]
我在Chrome上也是这个问题，帮忙看看怎么解决吧
