### ISSUE TITLE
Support for Strict mode in react 

### ISSUE THREAD

**Issue by SanjivG10** [nanxiaobei/antd-img-crop#178]
Once image gets uploaded, we get a modal that gives a warning that says: 

`findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of DomWrapper which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here`. 

[https://github.com/ant-design/ant-design/issues/26136](https://github.com/ant-design/ant-design/issues/26136) . This issue is from ant-design itself. I hope it gets resolved soon.

**Comment by nanxiaobei** [comment]
Yes, depends on `antd` solving that.
