### ISSUE TITLE
Canvas size error on Safari

### ISSUE THREAD

**Issue by bhtandev** [nanxiaobei/antd-img-crop#179]
Hi there, 
```
[Error] Unhandled Promise Rejection: InvalidStateError: The object is in an invalid state.
[Error] Unable to get image data from canvas. Requested size was 6749 x 6749
```
Reason for that is this: https://pqina.nl/blog/canvas-area-exceeds-the-maximum-limit/

Is it possible to scale the canvas size when on Safari?

**Comment by nanxiaobei** [comment]
Upgrade `antd-img-crop` to the latest version and try again.

If still happen, then the image maybe too large, can not support scale now.
