### ISSUE TITLE
The cropper disappear when upload a image 

### ISSUE THREAD

**Issue by cuong2001a** [nanxiaobei/antd-img-crop#181]
The image: https://i.pinimg.com/originals/6b/6f/ac/6b6fac2c5263b36cafbb8a6d13d19210.jpg
My code: 
```
<ImgCrop rotate>
    <Upload>
       <Button>Upload</Button>
    </Upload>
</ImgCrop>
```
The error: 
![image](https://user-images.githubusercontent.com/62129278/162925120-fbbb7f45-e734-429b-ad7f-6c9a4cab2033.png)
The cropper is just a tiny point in center with width = 0, and height = 0, I can't do anything. and when click ok to preview the image can't load

**Comment by nanxiaobei** [comment]
Can not reproduce on Chrome. maybe similar to this.
https://github.com/nanxiaobei/antd-img-crop/issues/177

**Comment by dangthaii** [comment]
> Can not reproduce on Chrome. maybe similar to this. #177

cuong2001a is my account, I saw that topic, and I understand that add transitionName="" and maskTransitionName="", but how to config that into <ImgCrop> like props of a Modal?

**Comment by nanxiaobei** [comment]
It is not supported at present to customize Modal props, may be added in the future.

**Comment by ianitararache** [comment]
Can we fix it ourselves? The error triggers quite a lot with large images. On Chrome / Firefox or Safari on Mac

**Comment by skyplor** [comment]
I had the same issue as well. Taking reference from #177, I created a PR for adding the 2 attributes to the AntModal. It seemed to have fixed this issue
