### ISSUE TITLE
Img-Crop 第一次加载， 不能加载 antd-modal 的样式， 导致位置跑到左下角。

### ISSUE THREAD

**Issue by skywalkeryin** [nanxiaobei/antd-img-crop#182]
错误：
![image](https://user-images.githubusercontent.com/18617857/163098472-c8e51238-f2b3-4db8-b57c-f33dc019255d.png)

只有在手动打开一个页面的modal后， 在打开Img-Crop后变的正常，可以加载antd-modal的css样式

**Comment by nanxiaobei** [comment]
需要手动引入样式文件：https://github.com/nanxiaobei/antd-img-crop#styles
