### ISSUE TITLE
beforeUpload 时给file添加了一个自定义属性，属性会丢失

### ISSUE THREAD

**Issue by baibaibai455** [nanxiaobei/antd-img-crop#184]
beforeUpload 时给file添加了一个自定义属性，在uploadOnChange的返回参数fileList 里这个自定义属性会丢失
<img width="556" alt="image" src="https://user-images.githubusercontent.com/47173675/165036465-2451bcba-5b09-40c6-a702-a14ee018b7f8.png">

**Comment by nanxiaobei** [comment]
请提供一个可复现的 demo

**Comment by baibaibai455** [comment]
> 请提供一个可复现的演示
https://codesandbox.io/s/a-li-yun-oss-antd-4-20-0-forked-6hwvgz?file=/demo.js:952-994

 请查看这个打印   console.log("Aliyun OSS:", fileList);

**Comment by nanxiaobei** [comment]
`console.log("Aliyun OSS:", fileList);` 这个打印的 `fileList[0]` 里是有 `url` 属性的

**Comment by baibaibai455** [comment]
> `console.log("Aliyun OSS:", fileList);` 这个打印的 `fileList[0]` 里是有 `url` 属性的

![image](https://user-images.githubusercontent.com/47173675/165048161-cee7d505-3546-4b77-8437-3ddd80be6c88.png)
第一个是没有的  导致请求 key: undefined

![image](https://user-images.githubusercontent.com/47173675/165048298-8c8f8dbe-4dbf-40b8-9fc7-5a6a1a522cf9.png)

**Comment by baibaibai455** [comment]
> > `console.log("Aliyun OSS:", fileList);` 这个打印的 `fileList[0]` 里是有 `url` 属性的
> 
> ![image](https://user-images.githubusercontent.com/47173675/165048161-cee7d505-3546-4b77-8437-3ddd80be6c88.png) 第一个是没有的 导致请求 key: undefined
> 
> ![image](https://user-images.githubusercontent.com/47173675/165048298-8c8f8dbe-4dbf-40b8-9fc7-5a6a1a522cf9.png)

![image](https://user-images.githubusercontent.com/47173675/165048998-dcc4c724-fcba-42b8-b002-81253042a7f1.png)

**Comment by nanxiaobei** [comment]
1. `onChange` 中第一次传入的 `file` 并非裁剪后的图片，而是原始图片，此情况比较复杂，暂无法解决。
2. 上文的 `key: undefined` 错误，是因为 `file` 对象是从 `getExtraData` 拿到的，此处也是原始图片，而非裁剪后的。
3. 目前只能保证在 `beforeUpload` 中拿到的 `file` 是裁剪后的图片，可对齐做相应处理。其它地方拿到的 `file` 都无法保证，无法一一去做兼容处理，破坏性太大。若有相关上传需求，可在 `beforeUpload` 处进行处理。

**Comment by baibaibai455** [comment]
> 1. `onChange` 中第一次传入的 `file` 并非裁剪后的图片，而是原始图片，此情况比较复杂，暂无法解决。
> 2. 上文的 `key: undefined` 错误，是因为 `file` 对象是从 `getExtraData` 拿到的，此处也是原始图片，而非裁剪后的。
> 3. 目前只能保证在 `beforeUpload` 中拿到的 `file` 是裁剪后的图片，可对其做相应处理。其它地方拿到的 `file` 都无法保证，无法一一去做兼容处理，破坏性太大。若有相关上传需求，可在 `beforeUpload` 处进行处理。

了解了，感谢您的回复
在不使用ImgCrop时uploadOnChange是拿到的是beforeUpload修改过的file，所以不太理解，那我在beforeUpload 里copy一份出来用uid做匹配
