### ISSUE TITLE
Antd Upload + antd-img-crop 裁剪后 data（file） 无url

### ISSUE THREAD

**Issue by 2449847346** [nanxiaobei/antd-img-crop#186]
步骤：
1、上传文件并裁剪；
2、beforeUpoad 中 设置文件url；
3、data 中file 设置oss 所需参数以及url；

期望结果：
data file 中含设置的url；

实际结果：
data中无url；

所使用版本：
antd | 4.20.3
React | react:"^16.13.1"
System | windows 10
Browser | chrome 101.0.4951.54

![167786060-eb495493-172a-47ca-8dae-b013958ab9d0](https://user-images.githubusercontent.com/54257812/168188990-4ea2c99e-a6fb-406b-8f76-ff16f19c6c58.png)

复现链接：
[https://codesandbox.io/s/unruffled-shaw-13gfw1?file=/src/App.js](url)

**Comment by nanxiaobei** [comment]
目前不支持 `data` 的参数 `file` 中获取到更新后的图片，也不太好支持。
可参考：https://github.com/nanxiaobei/antd-img-crop/issues/184#issuecomment-1109017409
