### ISSUE TITLE
FillColor does not appears to be working

### ISSUE THREAD

**Issue by onlyoneaman** [nanxiaobei/antd-img-crop#187]
When I write the code as shown to grab the image and filling fillColor
`  return (
    <ImgCrop
    fillColor="#000000"
    >
    <Upload />
    </ImgCrop>
  );`

The generated image does not appear to have the stated background. Instead, it shows the default white background.

**Comment by nanxiaobei** [comment]
can not reproduce.
please try the latest version `4.2.4`, if still not working, please provide a reproducible demo.
