### ISSUE TITLE
期望 feature：onModalOk 获取剪裁信息

### ISSUE THREAD

**Issue by roc-an** [nanxiaobei/antd-img-crop#189]
目前是在前端 canvas drawImage() -> toBlob() 进行的剪裁、转图片。

期望能获取到 canvas 剪裁的信息，剪裁坐标、宽高，然后由 RD 用户可以自行走服务端剪裁。

期望的 API 是：

- onModalOk 拿到剪裁信息。或者更优雅一点，将剪裁信息传递给 AntD Upload 组件的 data 函数。
- ImgCrop 可以加个属性：只获取剪裁信息，而不去处理原图

**Comment by nanxiaobei** [comment]
不是特别清楚希望获取那些信息。
可在源码中具体指出，或提交 PR。
https://github.com/nanxiaobei/antd-img-crop/blob/main/src/img-crop.tsx
