### ISSUE TITLE
移动端剪切定位不准确

### ISSUE THREAD

**Issue by chengluliu** [nanxiaobei/antd-img-crop#19]
你好, 组件在移动端的时候 剪切小窗和剪切定位不准确, 希望看一下,感谢

**Comment by q27488** [comment]
同样问题：
![image](https://user-images.githubusercontent.com/17950922/64680732-eb635900-d4b0-11e9-97c3-ae0ffcfbd292.png)
![image](https://user-images.githubusercontent.com/17950922/64680743-f0c0a380-d4b0-11e9-8096-e29b0d32ff9c.png)

**Comment by nanxiaobei** [comment]
你好，感谢反馈~
因为 Ant Design 本身是针对 PC 端中台设计的，没有考虑移动端。所以这个组件也没有测试过移动端，对移动端应该也不会做特殊兼容。
如果有问题的话，建议自行 fork 一份进行移动端测试和优化工作，谢谢。
