### ISSUE TITLE
customRequest is skipped when beforeCrop returns falsy

### ISSUE THREAD

**Issue by WenhanDo** [nanxiaobei/antd-img-crop#190]
I have a situation where only certain kind of images need cop and for others, cop is skipped by returning false in beforeCrop
but customRequest is skipped when beforeCrop returns false or a Promise that  resolves false

is this a feature or a bug?

**Comment by WenhanDo** [comment]
also, seems like beforeUpload is skipped too

**Comment by nanxiaobei** [comment]
when beforeCrop returns falsy, will stop the upload work.

**Comment by komarovalexander** [comment]
@WenhanDo instead of false, return the passed file and it will work 

```
	beforeCrop={(file) => file}
```
