### ISSUE TITLE
Proposal: Remove cropSize prop or allow null Override

### ISSUE THREAD

**Issue by lgants** [nanxiaobei/antd-img-crop#194]
The `cropSize` prop can become very problematic for images with certain dimensions - equidistant height/width works well, but others can be problematic. The [react-easy-crop](https://github.com/ricardo-ch/react-easy-crop) documentation on `cropSize` states (in bold text): "You should probably not use this option and should rely on aspect instead. See [ValentinH#186](https://github.com/ValentinH/react-easy-crop/issues/186.)". For example, the cropper overlay for some portrait images is zoomed in so far that this great library is essentially unusable 🙁. What are your thoughts on moving the spread `cropperProps` to the last position rather than the first - thereby allowing overrides? Seems like a very quick fix. I can raise a quick PR if so.

<img width="412" alt="Screen Shot 2022-08-10 at 9 59 04 PM" src="https://user-images.githubusercontent.com/18373573/184052490-9ef01090-175f-4b00-b48c-b7d007f7f825.png">

**Comment by lgants** [comment]
Also, forgot to mention that I'm using version `4.2.1` and here's the relevant code

````
<ImgCrop
  modalWidth={416}
>
 ...
````

**Comment by nanxiaobei** [comment]
`cropSize` is a very core prop, and the impact of deletion is uncontrollable.

**Comment by lgants** [comment]
hmm is there any willingness to support an override/escape hatch of some sort? My application needs to support user generate content, including brand logos. And, as you can see from the screen shoot, that is exceedingly hard with this library as currently configured. I would think others might have similar needs.

Also, I'm not saying `cropSize` should be removed. I just users should have the ability to override. Does that make sense? 

Thanks for the timely response btw!

**Comment by nanxiaobei** [comment]
There is not enough time and sufficient reason to make this modification. 
Maybe it will be added later, and of course, PR welcome.
