### ISSUE TITLE
Modal 中的 visible 替换成 open，以及其他 API 语法升级

### ISSUE THREAD

**Issue by dreammaker7** [nanxiaobei/antd-img-crop#197]
当前项目用的最新 4.23.1 antd 版本，调用裁剪 log 就抛语法废弃的异常，最近准备将API的语法更新到最新吗？

**Comment by dreammaker7** [comment]
Regarding this issue, I submitted a latest pull request. #199

**Comment by WildXBird** [comment]
+1

**Comment by nanxiaobei** [comment]
感谢，已升级至 `4.2.5`。
