### ISSUE TITLE
problem working with antd Form.Item

### ISSUE THREAD

**Issue by samankarbasi** [nanxiaobei/antd-img-crop#198]
hi
im working on a form that have nested Form List.
list of questions containing title, image, and list of options.
Upload component works fine when i just wrapped it in a Form.Item
but as long as i wrap Upload component inside a ImgCrop, antd form does not recognize it as form field anymore.

this works:
`<Form.Item
            name={[name, 'image']}
            label="image"
            fieldKey={[fieldKey, "image"]}
        >
            <Upload
                accept="image/*"
                customRequest={uploadImage}
                multiple={false}
                listType="picture-card"
                maxCount={1}
                onPreview={onPreview}
            >
                Upload
            </Upload>
        </Form.Item>
`

this does not:
`
<Form.Item
            name={[name, 'image']}
            label="image"
            fieldKey={[fieldKey, "image"]}
        >
            <ImgCrop>
                <Upload
                    accept="image/*"
                    customRequest={uploadImage}
                    multiple={false}
                    listType="picture-card"
                    maxCount={1}
                    onPreview={onPreview}
                >
                    Upload
                </Upload>
            </ImgCrop>
        </Form.Item>
`

**Comment by nanxiaobei** [comment]
`ImgCrop` is not an antd third-party form controls: https://ant.design/components/form/#components-form-demo-customized-form-controls

you need to implement it yourself with adding `value` & `onChange` props.
