### ISSUE TITLE
  Img crop component should return crop value

### ISSUE THREAD

**Issue by HuyAms** [nanxiaobei/antd-img-crop#20]
I do the crop on the backend side instead of frontend, so I need to send the original file with crop value. Could you expose the onChange function which returns crop value (x, y, width, height) and the original file? It would be nice if we also support the behavior like react-image-crop:

https://github.com/DominicTobias/react-image-crop

Thanks!

**Comment by nanxiaobei** [comment]
You mean `onChange` prop of the `Upload` component?
If so, sorry that `antd-img-crop` is designed to zero change to the `antd`'s component.
You can just fork and and the feature yourself.
