### ISSUE TITLE
cjs broken in 4.2.6

### ISSUE THREAD

**Issue by MadCcc** [nanxiaobei/antd-img-crop#203]
Reproduction: https://codesandbox.io/s/shang-chuan-qian-cai-qie-tu-pian-antd-4-23-5-forked-6rg8sl?file=/index.test.js

See error in test tab. 

And it works in 4.2.5: https://codesandbox.io/s/shang-chuan-qian-cai-qie-tu-pian-antd-4-23-5-forked-h8uhdj?file=/demo.js

**Comment by nanxiaobei** [comment]
Please try `4.2.7`.

**Comment by MadCcc** [comment]
Still not work: https://codesandbox.io/s/shang-chuan-qian-cai-qie-tu-pian-antd-4-23-5-forked-6rg8sl?file=/index.test.js

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/actions/runs/3263630742/jobs/5362970044

**Comment by nanxiaobei** [comment]
Fixed in `4.2.8`.

It's because upgraded to `rollup` 3.0, and the CommonJS export  of `antd` `LocaleReceiver` seems incompatible with it.

**Comment by nanxiaobei** [comment]
Fixed in `4.2.8`.

It's because upgraded to rollup 3.0, and the CommonJS export of `antd` `LocaleReceiver` seems incompatible with it.
