### ISSUE TITLE
使用umi ssr打包报错

### ISSUE THREAD

**Issue by hg542006810** [nanxiaobei/antd-img-crop#21]
报错如下![image](https://user-images.githubusercontent.com/16329156/65234727-b76ae200-db07-11e9-9ac5-2b1b3d7510f0.png)
直接跑项目是没问题的，但是一打包就报错。使用的架构，umijs 2.8.9，@umijs/plugin-prerender 1.4.2， antd 3.22.0

**Comment by nanxiaobei** [comment]
你好，本项目已经使用了 `babel-plugin-import`，查看 build 后的代码，也未发现引入 `antd` 整体。
请查看项目中其它设置，是否引入了 `antd` 整体，谢谢~
