### ISSUE TITLE
onModalOk not called

### ISSUE THREAD

**Issue by ZerosLifeCycle** [nanxiaobei/antd-img-crop#211]
![image](https://user-images.githubusercontent.com/23302959/203235643-c21a8811-210b-420a-9e41-e7190bf60a1d.png)

the callback function onModalOk is not working. but onModalCancel is working.
I need to do some logic in onModalOk function...

antd: 5.0.0
antd-img-crop: 4.5.1 or 4.5.0 or 4.4.0

**Comment by nanxiaobei** [comment]
this can not be reproduced. please provide a online reproducible demo.

**Comment by ZerosLifeCycle** [comment]
https://codesandbox.io/s/dawn-river-b5fc4k?file=/src/App.tsx @nanxiaobei

**Comment by nanxiaobei** [comment]
It's because that `beforeUpload` returns `false` in your demo.

In this line https://github.com/nanxiaobei/antd-img-crop/blob/main/src/ImgCrop.tsx#L248 
code will stop at here, so `onModalOk` will not execute.
