### ISSUE TITLE
Not able to use when upgrading from antd v4 to v5

### ISSUE THREAD

**Issue by iajaysharma** [nanxiaobei/antd-img-crop#212]
![image](https://user-images.githubusercontent.com/43104394/203298121-3813b9b5-b631-461a-9ac5-9d978d8fb367.png)

**Comment by nanxiaobei** [comment]
It's from `antd` source code I guess, because `antd-img-crop` does not have the `@babel/runtime` dep.
can refer https://www.google.com/search?q=Cannot+use+import+statement+outside+a+module

**Comment by iajaysharma** [comment]
So here is the solution:
If you are using this in Next js you need to use dynamic import to import "antd-img-crop" .
![image](https://user-images.githubusercontent.com/43104394/203701087-136e571d-12bf-44e6-a66e-89f30aed9c18.png)
