### ISSUE TITLE
最新版本的 ImgCropProps 没有导出了吗？

### ISSUE THREAD

**Issue by HowCanLove** [nanxiaobei/antd-img-crop#213]
![image](https://user-images.githubusercontent.com/15058500/204999636-a59c3401-bf07-4b9d-b5a0-49a4d81496c7.png)
![image](https://user-images.githubusercontent.com/15058500/204999731-c99eac11-f304-4da1-a87d-061cfe6d2e9c.png)

**Comment by nanxiaobei** [comment]
`4.5.2` 已修复。
