### ISSUE TITLE
server side rendering / import into node was recently broken

### ISSUE THREAD

**Issue by williamstein** [nanxiaobei/antd-img-crop#214]
Many thanks for antd-img-crop, which I really like and use at https://cocalc.com/config/account/avatar

Importing this package in node used to work:

```sh
mkdir tmp
cd tmp
npm init -y
npm install antd-img-crop@4.2.4
echo 'require('antd-img-crop')' > a.js
node a.js
```

Now it doesn't:

```sh
mkdir tmp2
cd tmp2
npm init -y
npm install antd-img-crop@latest
echo 'require('antd-img-crop')' > a.js
node a.js
/tmp/z3$ node a.js
/private/tmp/z3/node_modules/antd/es/locale-provider/LocaleReceiver.js:1
import _extends from "@babel/runtime/helpers/esm/extends";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/private/tmp/z3/node_modules/antd-img-crop/dist/antd-img-crop.cjs.js:21:22)

```

The problem is that something is getting confused between ES modules and CommonJS modules and loading the wrong thing.

It's nice to have node.js support, since it's needed for server side rendering, which can come up naturally when using next.js.

Please close this if you don't want to fix this, and I'll figure out how to restructure my app to work around this problem or just stick with an old version of antd-img-crop.

Thanks!

**Comment by williamstein** [comment]
I looked into this more and this really is a major bug your antd-img-crop library.  What happens is that the file `antd-img-crop/dist/antd-img-crop.cjs.js` in your npm module looks like this:
```js
...
var jsxRuntime = require('react/jsx-runtime');
var react = require('react');
var antd = require('antd');
var LocaleReceiver = require('antd/es/locale-provider/LocaleReceiver');
var AntModal = require('antd/es/modal');
...
```

The file `antd/es/locale-provider/LocaleReceiver` has "es" in its path and is literally the "ES module" version of that file.  The non-es module version is `antd/lib/locale-provider/LocaleReceiver`, and indeed directly in the terminal you can see that works fine:

```sh
/tmp/z5$ node
Welcome to Node.js v16.16.0.
Type ".help" for more information.
> require('antd/locale-provider/LocaleReceiver')
Uncaught Error: Cannot find module 'antd/locale-provider/LocaleReceiver'
Require stack:
- <repl>
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
> require('antd/lib/locale-provider/LocaleReceiver')
{
  default: [Function: LocaleReceiver],
  useLocaleReceiver: [Function: useLocaleReceiver]
}
```

ES modules versus Common JS modules are such a subtle pain.  This reminds me a lot of the python 2-->3 drama.

**Comment by williamstein** [comment]
I ended up making this https://www.npmjs.com/package/@cocalc/antd-img-crop in case anybody else runs into this issue.  After trying several things I gave up and just made the commonjs version a dummy function.  At least that doesn't crash.

**Comment by nanxiaobei** [comment]
can follow this solution: https://github.com/nanxiaobei/antd-img-crop/issues/212#issuecomment-1325973854

**Comment by ilik666** [comment]
@williamstein 
import ImgCrop from "@cocalc/antd-img-crop";

<ImgCrop> .... </ImgCrop>

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by williamstein** [comment]
Hi, here is the one commit I made to create the package @cocalc/antd-img-crop above:  

https://github.com/sagemathinc/antd-img-crop/commit/b3fef1503439fac3b99b556c42dd8c7c58e37495

It's what works for me.  Basically I replace the commonjs module with a dummy one.   I had forgot to push this commit before, so sorry if you looked for it and didn't find it.
