### ISSUE TITLE
Not working in next js

### ISSUE THREAD

**Issue by ilik666** [nanxiaobei/antd-img-crop#216]
//  [4.5.2](https://www.npmjs.com/package/antd-img-crop/v/4.5.2)
import ImgCrop from "antd-img-crop"; 

error - /Users/ildar/Desktop/magazine/node_modules/antd/es/locale-provider/LocaleReceiver.js:1
import _extends from "@babel/runtime/helpers/esm/extends";
^^^^^^
SyntaxError: Cannot use import statement outside a module

But works fine in version "3.16.0

**Comment by nanxiaobei** [comment]
can follow this: https://github.com/nanxiaobei/antd-img-crop/issues/212#issuecomment-1325973854

**Comment by ilik666** [comment]
this is not a solution, but a crutch

**Comment by nanxiaobei** [comment]
this is not a bug, and the error is from `antd` source code, no extra plan to fit it.
