### ISSUE TITLE
Skip Crop or Add Custom Footer

### ISSUE THREAD

**Issue by tragicmj** [nanxiaobei/antd-img-crop#218]
Is it possible in anyways to either add a skip option in ImageCrop or add customFooter and add different buttons in there?

                        <ImgCrop
                          aspect={1/1}
                          ref={this.imageCropper} 
                          shape='rect'
                          modalTitle="Crop Artwork"
                        >
                        <Upload
                          name="avatar"
                          listType="picture-card"
                          className="art-uploader"
                          showUploadList={false}
                          customRequest={this.onArtImageChange.bind(
                            this,
                            item.id
                          )}
                          id={"image-" + item.id}
                          style={{ width: '250px', height: '250px' }}
                        >
                         
                          </Upload>
                        </ImgCrop>

A modal opens on image select, so I need to add skip option in that, I tried beforeCrop prop but setting it true will simply not open the pop up and thus no further actions can be performed. I also tried adding customFooter by using customFooter as mentioned in antd Modals, but it didn't work.

**Comment by nanxiaobei** [comment]
1. why skip cop? it don't want to crop, I think you can just not using `ImgCrop`?
2. currently no way to add a customFooter for Modal, PR welcome.

**Comment by tragicmj** [comment]
Do not want to force user to crop image, so if they want they can crop it or else skip it

**Comment by nanxiaobei** [comment]
I think this is not a strong user demand, and there is no good UX for it.
If the user does not want to cut, he can directly click "OK" and upload. (although it is still cut, but it is insensitive to the user)

**Comment by Hamzakhann** [comment]
Its using ant modal so why we not getting okButtonProps and cancelButtonProps?
