### ISSUE TITLE
When width and height are specified the final image is scaled 

### ISSUE THREAD

**Issue by unvar** [nanxiaobei/antd-img-crop#22]
**Steps to Reproduce**:
* use `ImgCrop` with the following attributes: `width = 200` and `height = 200`
* upload an image larger than `200px` (say 1200x1600)
* resize the crop for full image width
* Click `Ok`

Expected:
* uploaded image is `200x200`

Actual:
* uploaded image is `1200x1200`

**Comment by nanxiaobei** [comment]
It's not a bug, but I will rethink what the behavior should be and give an update.

**Comment by unvar** [comment]
Thank you. I also updated my PR with your latest changes in case you want to take a look.
