### ISSUE TITLE
antd-img-crop中的Modal样式主题无法使用antd5全局化配置的

### ISSUE THREAD

**Issue by CristalFJJ** [nanxiaobei/antd-img-crop#224]
推测是因为引入的Modal不一样

antd-img-crop 引用 antd的modal
![image](https://user-images.githubusercontent.com/28974824/219293683-941d4356-8d6e-4696-8b7d-a7bfe3860cd7.png)

umi中使用antd5全局化注入配置
![image](https://user-images.githubusercontent.com/28974824/219294442-adefdaa3-1ee6-4468-bf94-712ac65a2672.png)

**Comment by nanxiaobei** [comment]
是的 ... 这是个比较复杂的问题。
其实之前  `esm` 文件引入的是 `antd/es/**` 源，但因为一些其它的问题（在 Next.js 中使用），又改成了 `antd/lib/**` 源。

目前似乎没有好的方案可以都适配，所以暂时应该不会改动。

**Comment by fc4soda** [comment]
弹窗标题等都可以用modalTitle来配置，但是Reset按钮没有配置项，要怎么修改语言呢？

**Comment by nanxiaobei** [comment]
@fc4soda 已更新 `4.12.2`，添加了 `resetText` 属性。
