### ISSUE TITLE
 苹果手机上传不裁剪旋转正常，裁剪旋转后会有白边 此时图片就成了黑图，安卓没问题 （测试机用的是苹果14）

### ISSUE THREAD

**Issue by Spring3bug** [nanxiaobei/antd-img-crop#226]

**Comment by Spring3bug** [comment]
![image](https://user-images.githubusercontent.com/37185894/220042188-ec6efa88-3d9b-45f2-8533-4b5fad9a7fac.png)  安卓是白底

**Comment by nanxiaobei** [comment]
填充色可使用 [`fillColor`](https://github.com/nanxiaobei/antd-img-crop#props) 属性传入，其实就是 canvas 的 [`fillStyle`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillStyle) 属性，没有其它处理。

可尝试此方案：https://stackoverflow.com/questions/52520599/canvas-colors-works-on-chrome-not-on-safari
