### ISSUE TITLE
antd/lib/locale-provider/LocaleReceiver 引用方式问题

### ISSUE THREAD

**Issue by Lucifier129** [nanxiaobei/antd-img-crop#227]
`antd/lib/locale-provider/LocaleReceiver` 的 exports 为 `{ default, useLocaleReceiver }`

`antd-img-corp` 通过 `import LocaleReceiver from 'antd/lib/locale-provider/LocaleReceiver'` 引用

经过 rollup 编译后变成 `var LocaleReceiver = require('antd/lib/locale-provider/LocaleReceiver')`

在 `next.js v12` 的 SSR 中会报错：

`Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.`

手动修改 `node_module/antd-img-crop` 为 `var LocaleReceiver = require('antd/lib/locale-provider/LocaleReceiver').default` 后，`next.js 12` SSR 正常了。

或许需要配置一下 rollup 支持 import default 和 module.exports 的兼容问题。

**Comment by nanxiaobei** [comment]
因为 `LocaleReceiver` 引入在 Next.js 中使用时引发问题很多，之前很多 issue 都是关于这个，而引入它只是为了定义默认的弹窗标题的语言。

另外 `antd` 也在更新关于 `locale` 功能的源代码，还在[这个文件](https://github.com/ant-design/ant-design/blob/master/components/locale-provider/index.ts)中注明留着是为了兼容 `antd-img-crop`。

所以考虑了一下，决定把 `LocaleReceiver` 的引入去掉了，使用 `navigator.language` 获取语言，已更新至 `4.7.0`。

但这样肯定无法与 `antd` 的 `locale` 完全一致（比如用户是中文浏览器但网站是英文），所以最稳妥的方式是传入 `modalTitle`。但考虑到引入 `LocaleReceiver` 的诸多问题，还是去掉先。

**Comment by Lucifier129** [comment]
Got it, thx
