### ISSUE TITLE
引入依赖报错

### ISSUE THREAD

**Issue by ptko5** [nanxiaobei/antd-img-crop#228]
AssertionError [ERR_ASSERTION]: filePath not found of /node_modules/antd/es/search

**Comment by ptko5** [comment]
antd版本为4.24.7

**Comment by nanxiaobei** [comment]
是否使用了 umi？请提供一个最小复现 demo

**Comment by ptko5** [comment]
使用umi了，把生成的.umi文件夹删除重新生成就可以了，谢谢。
