### ISSUE TITLE
Image crop modal not following antd theme

### ISSUE THREAD

**Issue by nonam4** [nanxiaobei/antd-img-crop#229]
Here's a [link](https://github.com/ant-design/ant-design/issues/41020) from an issue I've opened in antd repo.
And here is a [codesandbox](https://codesandbox.io/s/crop-image-before-uploading-antd-undefined-forked-u3gxro) link showing the problem.

The image cropper modal is not following antd ConfigProvider theme. As you can see, the config provider theme is dark but the cropper modal is in light theme.

**Comment by nanxiaobei** [comment]
Thanks for your feedback.
Fixed, please try the `4.8.0` version.
