### ISSUE TITLE
裁剪宽高问题、升级 antd 报错问题

### ISSUE THREAD

**Issue by 13164286167** [nanxiaobei/antd-img-crop#232]
**之前我提过关于固定裁剪宽高无法设置的问题(https://github.com/nanxiaobei/antd-img-crop/issues/171)**

1. 由于业务需要裁剪固定宽高的图片，所以我必须要采用可以设置 width,height 的版本，V2.5.0。在 antd 4.x 版本中使用良好。

2. 现在项目中 antd 从 V4.21.3 升级到 V5.3.0 后，antd-img-crop V2.5.0 版本报错： 

- 源码： 
  import { Upload } from 'antd';
  import ImgCrop from 'antd-img-crop';
  <ImgCrop {...cropProps}> <Upload.Dragger {...props} /> \</ImgCrop>

- 报错：
  Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead.

- 去掉 ImgCrop， 只保留 <Upload.Dragger {...props} />  后报错消失。

3. antd-img-crop 升级到最新版本 V4.8.0
- 不报错了，但是新版本好像还是不可以设置裁剪的宽高（设置不生效），aspect 无法满足固定裁剪尺寸的需求（需求举例： 不论上传多大的图片，都裁剪区域都是 1124 * 840 ）。

**大佬救救弟弟，给支个招，antd-img-crop 是新版本有办法可以支持固定宽高，还是旧版本怎么能处理这个错误。**
**弟弟先谢过了!!!**

**Comment by nanxiaobei** [comment]
因为 v2 与现在用的底层裁切库不同，现在用的是 [`react-easy-crop`](https://github.com/ValentinH/react-easy-crop)，所以不支持 `width` `height` 设置了。

但 `antd-img-crop` 提供了 `cropperProps` 属性，可直接将 `react-easy-crop` 的 props 传入。

解决方案是：

1. 升级到 `antd-img-crop` 到 `4.9.0`（`4.9.0` 源码中不设置 `cropSize` 了）
2. 自行通过 `cropperProps`，传入 `react-easy-crop` 的 `cropSize` 和 `onCropSizeChange`（请查阅 [`react-easy-crop` 文档](https://github.com/ValentinH/react-easy-crop#props)）
3. 当请注意文档中，`cropSize` 的 Description 里注明了[可能有 bug](https://github.com/ValentinH/react-easy-crop/issues/186)，推荐使用 `aspect`（这也是为什么 `antd-img-crop` 只实现了 `aspect`）
