### ISSUE TITLE
[Feature Request] - Reset Button

### ISSUE THREAD

**Issue by Hawiie13** [nanxiaobei/antd-img-crop#233]
When you messed up with the zoom or rotation, you can reset the to start again.
maybe a button that will on the left side of the cancel button

![image](https://user-images.githubusercontent.com/6790102/226076153-05a7dde6-0528-48ce-94e4-9995d062d137.png)

**Comment by nanxiaobei** [comment]
thanks for your suggesstion, added `showReset` prop to `4.10.0`.
