### ISSUE TITLE
某些情况下组件使用了rem单位，样式混乱

### ISSUE THREAD

**Issue by cmmmmmmmmmmmmmmmmmmmmmmmm** [nanxiaobei/antd-img-crop#237]
在某些情况下组件会自动添加上 [&~section:first-of-type]:mt-4 [&~section:last-of-type]:mb-4 类名（偶发），使用了rem为单位的样式，我们的项目中有设置根节点字体大小为100px，导致样式混乱
``
![image](https://user-images.githubusercontent.com/108503920/229010153-7958804d-01bf-47d2-8163-51e27dc65426.png)
![image](https://user-images.githubusercontent.com/108503920/229010167-184f44d1-14bf-48ca-907c-9a1c4c0325df.png)

**Comment by nanxiaobei** [comment]
组件使用了 Tailwind CSS，可自动覆盖，目前暂无更改计划。
