### ISSUE TITLE
怎么实现限制非png文件上传时不显示裁剪弹窗并且忽略上传文件

### ISSUE THREAD

**Issue by lovehebe330** [nanxiaobei/antd-img-crop#238]
打算实现上传前判断文件格式，如果为非png的话不显示裁剪弹窗并且忽略上传文件Upload.LIST_IGNORE，但是
![image](https://user-images.githubusercontent.com/20655248/229750648-98637a94-baff-462f-8c0b-fe9cab663fbe.png)
发现这样写还是显示出裁剪弹窗

**Comment by nanxiaobei** [comment]
感谢反馈，`4.12.0` 已更新，保持 `beforeCrop` 中代码即可。

`beforeCrop` 与 `beforeUpload` 行为将一致，在 `beforeUpload` 前执行，所以理论上 `beforeUpload` 中将不用再判断 isPNG。
