### ISSUE TITLE
Issue with Tailwindcss

### ISSUE THREAD

**Issue by matteomaiocchi99** [nanxiaobei/antd-img-crop#239]
Hi, we have discovered a compatibility issue with projects that already use tailwind and your image cropper. In the rollup of your build, tailwind style is injected, and at that point, since your style is injected after our project's, your style takes priority and overrides some tailwind classes (such as the hidden class). One possible solution could be to provide a props to pass to the image cropper component to tell it whether to include or remove the style.

Attachment 1: Screenshot of the style that is causing issues
Attachment 2: Screenshot of the project with antd-img-crop and the non-functioning hidden class
Attachment 3: Screenshot obtained by removing the code from Attachment 1 or moving it as the first injected style.

![Screenshot 2023-04-06 alle 09 19 33](https://user-images.githubusercontent.com/98943607/230305711-2c81f96b-0191-4098-a894-d5efe2b3c9ca.png)
![Screenshot 2023-04-06 alle 09 24 19](https://user-images.githubusercontent.com/98943607/230305787-81a96ab3-9618-441c-a56c-2c2ec3cdc3ac.png)
![Screenshot 2023-04-06 alle 09 24 44](https://user-images.githubusercontent.com/98943607/230305814-b8d5af3a-a7ec-4d3b-8aa9-21834d402457.png)

**Comment by nanxiaobei** [comment]
Sorry but I did not get the exact information. 
I'd like to know the exact class which is causing the problem (because `antd-img-crop` did not use `.hidden`), or provide a minimum recurrence demo

**Comment by matteomaiocchi99** [comment]
Here two demo links: 
with img crop and tailwind broken : https://stackblitz.com/edit/react-i5rg76?file=src%2Findex.js,public%2Findex.html,src%2FApp.js
without img-crop and everything work fine: https://stackblitz.com/edit/react-kh4plh?file=src%2Findex.js,public%2Findex.html,src%2FApp.js
