### ISSUE TITLE
点了取消按钮，图片还是会加入到文件列表中，并且还执行了上传操作，但是没有经过 beforeUpload 钩子

### ISSUE THREAD

**Issue by tanggd7** [nanxiaobei/antd-img-crop#242]
我看 4.11 的版本当选择取消时，图片并不会加入到文件列表中，也不会触发上传操作。但是我用了最新版的包，确会出现这个情况，主要他还没有触发 beforeUpload 这个钩子，所以也没有办法终止上传这个动作。

**Comment by nanxiaobei** [comment]
https://4qoom5p9x4.csb.app/

目前的最新版本，点击取消没有上传，可以在上面试

**Comment by StanLxXX** [comment]
我用 4.11和最新版都会出现这个问题，不知道哪里出问题了

**Comment by StanLxXX** [comment]
> 我也搞不清楚啥问题，可能和其他包冲突了？

不清楚，我还在想办法怎么拦截住，目前没拦住

**Comment by caoyang131** [comment]
> 在 `beforeUpload` 里 return `Upload.LIST_IGNORE` 可拦截。 https://ant.design/components/upload-cn#api

Upload.LIST_IGNORE从antd 4.13.0开始支持，低于此版本的antd可将裁剪组件回退至4.10.2版本以规避此问题
