### ISSUE TITLE
TS error TS2322 Type '{ children: Element }' is not assignable to type 'IntrinsicAttributes & ImgCropProps'.   Property 'children' does not exist on type 'IntrinsicAttributes & ImgCropProps'.

### ISSUE THREAD

**Issue by 986982229** [nanxiaobei/antd-img-crop#251]
package.json 如下：
react: ^16.8.6,
"antd": "4.24.12",
"antd-img-crop": "^3.2.0",   // yarn之后的版本是3.16.0
"eslint": "^8.43.0",
"eslint-plugin-react": "^7.32.2",
"typescript": "^4.9.5",
"@types/react": "^18.0.9",

tsconfig.json如下：
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "esModuleInterop": true,
    "resolveJsonModule": true, // 能够使用 import ss from "*.json"
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "@@/*": ["./src/.umi/*"]
    },
    "strict": true,
    "alwaysStrict": true,
    "strictNullChecks": true,
    "strictPropertyInitialization": true,
    "strictFunctionTypes": false,
    "outDir": "dist/2c",
    "noImplicitAny": false,
    "target": "ES5",
    "rootDir": "src",
    "moduleResolution": "Node",
    "types": [],
    "skipDefaultLibCheck": true,
    "skipLibCheck": true,
    "noFallthroughCasesInSwitch": true, // 检查switch语句包含正确的break
    "allowUnreachableCode": false, // 检查不可达代码；true：忽略不可达代码，false：不可达代码将引起错误
  },
  "include": ["src/**/*.ts", "src/**/*.tsx"],
  "exclude": [
    "node_modules", // 排除 node_modules 文件夹
    "$node_modules", // 排除 node_modules 文件夹
    "node_modules/@umijs",
    "node_modules/@types",
    "dist", // 排除 dist 文件夹
    "src/.umi/*",
    "src/pages/locales/*",
    "src/utils/Helper.ts"
  ],
}

代码如下：
```
<ImgCrop
  shape='rect'
  zoom={true}
>
  <Upload
    accept="image/*"
    listType="picture-card"
    beforeUpload={beforeUpload}
  >
    <button id='uploadAvatarBtnId' />
  </Upload>
</ImgCrop>
```

运行命令：tsc    报错如下：
error TS2322: Type '{ children: Element; shape: "rect"; zoom: true; }' is not assignable to type 'IntrinsicAttributes & ImgCropProps'.
  Property 'children' does not exist on type 'IntrinsicAttributes & ImgCropProps'.

不知该如何解决

**Comment by nanxiaobei** [comment]
可以重启一下 TS 试试。
若还是存在，麻烦提供一个可复现的 demo。
