### ISSUE TITLE
Show crop modal only for case when image did not pass validation

### ISSUE THREAD

**Issue by komarovalexander** [nanxiaobei/antd-img-crop#254]
hi team, is there a way to check if image is valid and if it is valid then upload it without crop modal to be shown, and if it is not valid then show crop modal?
awesome library!
thanks

**Comment by nanxiaobei** [comment]
can use `beforeCrop` to decide whether to open modal.

https://github.com/nanxiaobei/antd-img-crop#props

**Comment by komarovalexander** [comment]
Hi @nanxiaobei thanks for the answer, but in that case customRequest will not work https://github.com/nanxiaobei/antd-img-crop/issues/190

but as image is valid it should upload the image, can you advice a solution, thanks!

**Comment by nanxiaobei** [comment]
Sorry but currently I have no time to support this feature.
