### ISSUE TITLE
使用antd": "4.22.4", 剪裁弹窗点击取消后仍然会触发onChange事件进行上传操作

### ISSUE THREAD

**Issue by sanxyzhang** [nanxiaobei/antd-img-crop#263]

**Comment by sanxyzhang** [comment]
并不生效，仍然会触发onChange事件
` 
const [cancelUpload, setCancelUpload] = useState<boolean>(false);
const handleChange: UploadProps['onChange'] = useCallback(async info => {
        if (cancelUpload) {
            return;
        }
        setUploading(true);
        const {status: fileStatus, response, type, name, percent} = info.file;
        setFileName(name);
        setUploadPercent(percent);
        if (type.includes('image')) {
            getBase64(info.file.originFileObj as RcFile, url => {
                setPreviewImgUrl(url);
            });
        }
        const formatInfoList = _.map(info.fileList, fileItem => {
            const {status, response = {}} = fileItem;
            // 判断是否上传完成
            const isDone = status === UPLOAD_STATUS.DONE;
            // 上传完成且res code === 0才是成功
            const formatStatus = response.code !== SUCCESS_CODE ? UPLOAD_STATUS.ERROR : status;
            return {
                ...fileItem,
                status: isDone ? formatStatus : !status ? UPLOAD_STATUS.ERROR : status,
                errorText: _.get(response, 'message.global', '') || fileItem.errorText
                    || (status === UPLOAD_STATUS.ERROR ? ERROR_TEXT.NETWORK_ANOMALY : '')
            };
        });
        dispatch(actions.updateMaterialsUploadInfo(formatInfoList));
        if (fileStatus === UPLOAD_STATUS.ERROR) {
            toastErrorMessage(response?.message || '上传失败');
            setErrorInfo({
                fileName: name,
                message: response.message.global
            });
        }
        else if (fileStatus === UPLOAD_STATUS.DONE) {
            setUploading(false);
            const {code} = response as UploadResponse;
            if (code === SUCCESS_CODE) {
                setCanReload(true);
                const fileUrl = (_.get(response, 'result.url') || _.get(response, 'result.fileUrl')) as string;
                const extra = _.get(response, 'result', {});
                onFileDone && onFileDone(fileUrl, extra);
                onChange && onChange(fileUrl);
                if (_.get(extraData, 'type') === 'audio') {
                    setAudioUrl(fileUrl);
                }
                if (_.get(extraData, 'type') === 'video') {
                    setVideoUrl(fileUrl);
                }
                setErrorInfo(null);
                return;
            }
            setErrorInfo({
                fileName: name,
                message: response.message.global
            });
            toastErrorMessage(response?.message || '上传失败');
        }
    }, [extraData, cancelUpload, dispatch, onFileDone, onChange]);
const beforeUpload = useCallback((file: RcFile, fileList: RcFile[], showMsg: boolean = true) => {
        message.config({
            duration: 2,
            maxCount: 3
        });
        const nameReg = /^[\u4E00-\u9FA5a-zA-Z0-9-_]{1,100}$/;
        if (!nameReg.test(_.replace(file.name, /\.[^.]*$/, ''))) {
            message.error(ERROR_TEXT.NAME_ERROR_TEXT);
            !usingCardStyle && handleInvalidData({file, errorText: ERROR_TEXT.NAME_ERROR_TEXT});
            return cut && showMsg ? false : Upload.LIST_IGNORE;
        }
        const fileSize = file.size / 1024 / 1024;
        if (_.some(fileRegexList, (item: RegExp) => item.test(file.type))) {
            if (maxFileSize && fileSize > maxFileSize) {
                message.warning(`上传文件大小不要大于${maxFileSize}MB`);
                return cut && showMsg ? false : Upload.LIST_IGNORE;
            }
            else if (file.type.includes('video')) {
                if (fileSize > FILE_MAX_SIZE.VIDEO || !_.includes(FILE_TYPE.VIDEO, getFileExtension(file.name))) {
                    // eslint-disable-next-line max-len
                    const errorText = fileSize > FILE_MAX_SIZE.VIDEO
                        ? ERROR_TEXT.SIZE_ERROR_TEXT + SIZE_ERROR_OBJ.VIDEO
                        : ERROR_TEXT.TYPE_ERROR_TEXT;
                    message.warning(errorText);
                    handleInvalidData({file, errorText});
                    return cut && showMsg ? false : Upload.LIST_IGNORE;
                }
            }
            else if (file.type.includes('audio')) {
                if (fileSize > FILE_MAX_SIZE.AUDIO || !_.includes(FILE_TYPE.AUDIO, getFileExtension(file.name))) {
                    // eslint-disable-next-line max-len
                    const errorText = fileSize > FILE_MAX_SIZE.AUDIO
                        ? ERROR_TEXT.SIZE_ERROR_TEXT + SIZE_ERROR_OBJ.AUDIO
                        : ERROR_TEXT.TYPE_ERROR_TEXT;
                    message.warning(errorText);
                    handleInvalidData({file, errorText});
                    return cut && showMsg ? false : Upload.LIST_IGNORE;
                }
            }
            else if (file.type.includes('image')) {
                if (fileSize > FILE_MAX_SIZE.IMAGE || !_.includes(FILE_TYPE.IMAGE, getFileExtension(file.name))) {
                    // eslint-disable-next-line max-len
                    const errorText = fileSize > FILE_MAX_SIZE.AUDIO
                        ? ERROR_TEXT.SIZE_ERROR_TEXT + SIZE_ERROR_OBJ.IMAGE
                        : ERROR_TEXT.TYPE_ERROR_TEXT;
                    message.warning(errorText);
                    handleInvalidData({file, errorText});
                    return cut && showMsg ? false : Upload.LIST_IGNORE;
                }
            }
        }
        if (onBeforeUpload) {
            return onBeforeUpload(file, fileList);
        }
        // else {
        //     message.warning(ERROR_TEXT.TYPE_ERROR_TEXT);
        //     handleInvalidData({file, errorText: ERROR_TEXT.TYPE_ERROR_TEXT});
        //     return Upload.LIST_IGNORE;
        // }
        backUpload && message.warning('上传完成前不要离开本界面');
        return true;
    }, [backUpload, fileRegexList, cut, handleInvalidData, maxFileSize, onBeforeUpload, usingCardStyle]);
const uploadEle = useMemo(() => {
        const wrapperCls = classnames(`file-upload-wrap ${className}`, {error: !!errorFileInfo});
        return (
            <Upload
                className={wrapperCls}
                action={uploadUrl}
                showUploadList={showUploadList}
                fileList={uploadInfo}
                accept={accept}
                data={formatUploadData}
                headers={{
                    ...headers
                }}
                onChange={handleChange}
                beforeUpload={(...params) => beforeUpload(...params, !cut)}
                // 不展示fileList
                {...(usingCardStyle
                    ? {listType: 'picture-card'}
                    : {itemRender: () => null})
                }
                {...extraAntdProps}
            >
                {usingCardStyle
                    ? uploadCardWithProps
                    : (
                        <div className="upload-wrapper">
                            {children || (
                                <Button
                                    className="upload-btn"
                                    icon={uploadButtonIcon
                                        ? <CustomIcon iconType={uploadButtonIcon} /> : <UploadOutlined />
                                    }
                                >
                                    {btnText || '上传文件'}
                                </Button>
                            )}
                        </div>
                    )}
            </Upload>
        );
    }, [accept, btnText, children, className, errorFileInfo, extraAntdProps, cut,
        headers, showUploadList, uploadButtonIcon, uploadInfo, uploadCardWithProps,
        uploadUrl, usingCardStyle, formatUploadData, handleChange, beforeUpload]);

    return (
        <div className="upload-with-tip-wrapper">
            {cut ? (
                <ImgCrop
                    {...DEFAULT_CUT_PROPS}
                    {...cutProps}
                    beforeCrop={beforeUpload}
                    onModalCancel={() => setCancelUpload(true)}
                >
                    {uploadEle}
                </ImgCrop>
            ) : uploadEle}
            {uploadTip && <div className="upload-bottom-tip">{uploadTip}</div>}
        </div>
    );
};`

**Comment by sanxyzhang** [comment]
并不会生效，仍然会触发onChange事件。

**Comment by nanxiaobei** [comment]
我刚试了一下 `antd@4.22.4` + `antd-img-crop` 最新版，是正常的。
看一下 `antd-img-crop` 是否是最新版，如果还有问题，可以提供一个复现的在线 demo。

**Comment by nanxiaobei** [comment]
@sanxyzhang `4.21.0` 中已修复。

**Comment by pisyell** [comment]
4.22.0 版本仍会触发，触发方式是 antd-img-crop不是作为“一手”引入项目的，而是作为“二手”，比如：antd-img-crop在内部组件库中A组件使用并随着一起打包，然后将A组件引入项目中，此时点击取消就会触发 onChange。还有就是此时antd-img-crop也读不到ConfigProvider的配置，导致中英文不对，这个怎么解决？

**Comment by pisyell** [comment]
@nanxiaobei

**Comment by cloudGrin** [comment]
在以下版本仍然遇到该问题，通过onModalCancel 中手动调用 resolve(Upload.LIST_IGNORE)解决了

"antd": "^5.21.6",
"antd-img-crop": "^4.23.0"
