### ISSUE TITLE
Is there a way to move the crop square over the image/canvas. Rather than zooming into the image and then moving it

### ISSUE THREAD

**Issue by Joshuajrodrigues** [nanxiaobei/antd-img-crop#264]
The reason is that im dealing with a large image and i need to crop a part of it and zooming in causes lag possibly due to re draws ? And safari mobile can only handle canvas size of max 4000 ish pixels.

**Comment by nanxiaobei** [comment]
Sorry but `antd-img-crop` uses `react-easy-crop` as its underlying crop lib, as `react-easy-crop` not supported it, so can not use it this way.
