### ISSUE TITLE
beforeUpload 返回了false，但依然发起上传

### ISSUE THREAD

**Issue by liuyan0535** [nanxiaobei/antd-img-crop#267]
版本：antd 4.24.15 + antd-img-crop 4.18.0；
问题：beforeUpload 返回了false，但依然能发起上传。 只使用antd Upload组件是正常的，beforeUpload 为false时，不会进行上传。

**Comment by Memories-SlowFever** [comment]
在beforeUpload里是不是 const handleBeforeUpload = （）=> {
   if (xxx) {
    return  false
   }
  return  true
};
我是这样的没问题，还有是不是正常使用了customRequest

**Comment by nanxiaobei** [comment]
请提供一个可复现的最小 demo

**Comment by cai-zhuo** [comment]
找到bug了，是因为 `onModalCancel` 执行的时候，试图调用 `resolve(Upload.LIST_IGNORE)` 组织更新文件列表，但是这个时机已经不是 AntdUpload 的 `beforeUpload` 阶段了，所以没有成功阻止上传
一时没有想到影响范围小的解决方法，也没有测试帮忙兜底，作者有办法解决下吗 @nanxiaobei

**Comment by nanxiaobei** [comment]
我无法复现这个场景。

**Comment by yanthink** [comment]
我也遇到一样的问题，点击取消也会上传图片

**Comment by yanthink** [comment]
resolve(Upload.LIST_IGNORE) 可以改成 resolve(false) 吗？

**Comment by nanxiaobei** [comment]
请利用 codesandbox 提供最小的复现 demo

**Comment by yanthink** [comment]
> 请利用 codesandbox 提供最小的复现 demo

在 codesandbox 测试没有出现这个问题，但是我本地使用 next.js 就会出现取消也会上传的问题

https://codesandbox.io/p/devbox/antd-img-crop-yjpc3t

https://github.com/nanxiaobei/antd-img-crop/assets/9098321/84f5a2eb-19ff-4078-b472-10f31a33f02b

**Comment by nanxiaobei** [comment]
对于 Next.js 中遇到此问题的情况，请参考：

https://github.com/nanxiaobei/antd-img-crop/issues/259#issuecomment-1794509058

**Comment by nanxiaobei** [comment]
@cai-zhuo 请利用 codesandbox 提供一个最小可复现 demo
