### ISSUE TITLE
Uncaught Error: 'children' to 'ImgCrop' must be 'Upload' or 'Upload.Dragger'

### ISSUE THREAD

**Issue by qianyx21** [nanxiaobei/antd-img-crop#27]
我代码是这样写的，是包裹了Uplaod的
`
<ImgCrop
  width={cropWidth}
  height={cropHeight}>
  <Upload
    action={isWx ? "/api/uploadToWx": url}
    listType="picture-card"
    fileList={list}
    data={extraData}
    onPreview={this.handlePreview}
    onChange={v => {
    // console.log("上传改变", list, fileList);
    let file = v.file, fileList = v.fileList;

    let index = _.findIndex(fileList, item => item.uid == file.uid);
    if(file){
      if(file.status === "done"){
        // console.log("上传成功", v.file);
        let response = v.file.response;
        if(response && response.status === "success"){
          let fileItem = {
            uid: file.uid,
            url: response.url,
            status: "done",
          };
          if(isWx){
            fileItem.wx = response.wx;
          }
          fileList[index] = Object.assign(fileItem);
        }
      }else if(file.status === "uploading"){
        fileList[index] = Object.assign({
          uid: file.uid,
          // url: "",
          status: "uploading",
        });
      }
    }
    // console.log("上传组件的值改变", newValue);
    onChange(fileList);
  }}
>
{list.length >= num ? null : uploadButton}
</Upload>
</ImgCrop>
`

**Comment by nanxiaobei** [comment]
看一下这个 Upload 是否经过封装，
若没有，试着先根据示例 https://codesandbox.io/s/antd-img-crop-4qoom5p9x4，放一个最基本的 Upload 组件，
然后改变 props，看看是哪一步出错

**Comment by qianyx21** [comment]
之前是2.3.0，我改成2.1.2之后就可以了
