### ISSUE TITLE
next.js 中 modal 取消还是会发起上传请求，onModalCancel resolve 并没有效果

### ISSUE THREAD

**Issue by yanthink** [nanxiaobei/antd-img-crop#270]
<img width="375" alt="image" src="https://github.com/nanxiaobei/antd-img-crop/assets/9098321/d1ec45f3-b376-4bf6-a9af-d0cdb36b589b">

Promise 中多次 resolve 并没有效果

<img width="324" alt="image" src="https://github.com/nanxiaobei/antd-img-crop/assets/9098321/a991fe72-6d7b-44c3-b241-e2640368a55f">

**Comment by nanxiaobei** [comment]
已在 `4.21.0` 中修复。
