### ISSUE TITLE
When uploading a PNG image, its size almost doubles.

### ISSUE THREAD

**Issue by xinyiii1130** [nanxiaobei/antd-img-crop#276]
The size of the png image increased almost twice when I upload it. For jpeg image and jpg image is fine, only PNG image.

This is the image I used.
![wetalk2](https://github.com/nanxiaobei/antd-img-crop/assets/86938805/05ec93a5-8614-4817-a712-8320cc59970c)

The original file size is 3.6MB.
![image](https://github.com/nanxiaobei/antd-img-crop/assets/86938805/7d2ca184-c82b-4a88-bfe0-98cf2d5f1b09)
![image](https://github.com/nanxiaobei/antd-img-crop/assets/86938805/37b1fa77-2eef-4005-a377-59570055c191)

The size of uploaded image is 6204448 byte, which is 5.91 MB.
![image](https://github.com/nanxiaobei/antd-img-crop/assets/86938805/c765b9f9-8c64-4d03-9413-5a53939b97b7)

**Comment by nanxiaobei** [comment]
you can set `quality` prop or use `beforeUpload` to optimize it

```jsx
<Upload
  beforeUpload={(oldFile)=> {
    const newFile = reduceSize(oldFile) // process oldFile
    return newFile
  }}
/>
```

**Comment by priesty** [comment]
> ```js
> reduceSize
> ```

quality 设置多少呢，reduceSize又是咋处理的

**Comment by SummerLiu95** [comment]
> you can set `quality` prop or use `beforeUpload` to optimize it
> 
> <Upload
>   beforeUpload={(oldFile)=> {
>     const newFile = reduceSize(oldFile) // process oldFile
>     return newFile
>   }}
> />

尝试使用 quality，发现并没有任何作用，quality 设置为 0.2 还有 0.8，oldFile 的 size 都是一样
