### ISSUE TITLE
ImgCrop 嵌套 Antd Dragger组件时，ImgCrop组件的onModalOK事件不会触发

### ISSUE THREAD

**Issue by li1870959** [nanxiaobei/antd-img-crop#279]
1、ImgCrop 嵌套 Antd Dragger组件时，ImgCrop组件的onModalOK事件不会触发
2、以下是我的实际代码预览链接：  https://codesandbox.io/p/sandbox/github-antd-img-crop-bug-mjjlwy?file=%2Fsrc%2FsearchByImage%2Findex.jsx%3A70%2C9-70%2C18

**Comment by nanxiaobei** [comment]
是 `onModalOk`，不是 `onModalOK`，`k` 小写
与 `antd` 的 `onOk` 的 `k` 小写保持一致

**Comment by li1870959** [comment]
谢谢，是我没注意，不好意思

**Comment by li1870959** [comment]
> 是 `onModalOk`，不是 `onModalOK`，`k` 小写 与 `antd` 的 `onOk` 的 `k` 小写保持一致

谢谢，是我没注意，不好意思
