### ISSUE TITLE
'children' to 'ImgCrop' must be 'Upload' or 'Upload.Dragger'

### ISSUE THREAD

**Issue by chao-wu** [nanxiaobei/antd-img-crop#28]
'children' to 'ImgCrop' must be 'Upload' or 'Upload.Dragger'

      <>
        <ImgCrop>
          <Upload
            listType="picture-card"
          >
            ++++++++++
          </Upload>
        </ImgCrop>
      </>

**Comment by nanxiaobei** [comment]
Thank you for your feedback, please upgrade to `2.3.1` to solve this.
