### ISSUE TITLE
upload file validation not working while using antd-img-crop

### ISSUE THREAD

**Issue by naem-Cefalo** [nanxiaobei/antd-img-crop#281]
I am using img-crop in a antd form but it not triggering the validation . In picture I already  have uploaded the photo but error message not removed. 
![Screenshot 2024-03-22 at 3 38 39 PM](https://github.com/nanxiaobei/antd-img-crop/assets/114467459/806e79cb-d24e-4127-9e46-7f03119a7dbd)

Its my first time opening a issue in a open source project. If I miss something let me guid plz

**Comment by nanxiaobei** [comment]
https://github.com/nanxiaobei/antd-img-crop/issues/148#issuecomment-888199345
