### ISSUE TITLE
open crop modal with defaultFileList props

### ISSUE THREAD

**Issue by tomasnikl** [nanxiaobei/antd-img-crop#287]
Hi,

is it possible to open a modal for cropping automatically if only one file is defined in defaultFileList?

```
<ImgCrop aspect={aspect}>
	<Upload.Dragger
		accept={accept}
		defaultFileList={[{
			uid: 'foo1',
			name: 'foo1.png',
			status: 'done',
			url: 'https://example.com/image.png',
			thumbUrl: 'https://example.com/image.png',
		}]}
	>
		Click/Drag to upload
	</Upload.Dragger>
</ImgCrop>
```

the reason is the following: 
I know the url of the image when I load the component and I want to crop this image

**Comment by nanxiaobei** [comment]
I think you can directly do it like this in current verison?

**Comment by RezaGhx** [comment]
hey @nanxiaobei 
I wanna report an issue but I'm my time is running out. your `onModalCancel` is uploading the image anyway, as it should close the cropper modal only. do you know how to fix it?

**Comment by du937935598** [comment]
After popping up the cropping, drag and zoom in, then click the button to shrink it. It cannot be shrunk to 1, but can only be shrunk to 1.1. What should I do

**Comment by nanxiaobei** [comment]
`onModalCancel` will ignore the upload
