### ISSUE TITLE
Extra functionality from `react-image-crop` and modal customization

### ISSUE THREAD

**Issue by abdullah-K** [nanxiaobei/antd-img-crop#29]
Is there a way to use the underlying properties of the `react-image-crop` such as `minHeight`, `minWidth`, etc. since this package depends on it? Also, is there a way to customize the Modal component that shows up when cropping (changing the buttons and footer, for example)?
Thank you!

**Comment by nanxiaobei** [comment]
There is no such abilities now, Because the philosophy of this component is less API, you can fork and add it yourself.
