### ISSUE TITLE
Image cropper modal reset button doesn't align with cancel and save buttons when using Safari/iOS.

### ISSUE THREAD

**Issue by kimly888** [nanxiaobei/antd-img-crop#296]
Reset button doesn't align with the cancel and save buttons when using Safari/iOS.

Chrome/Arc: OK
<img width="602" alt="Screenshot 2024-09-13 at 3 57 13 PM" src="https://github.com/user-attachments/assets/8f9df58c-b42e-4cc5-b7e2-bb657f70c59b">

Safari: Not OK
<img width="602" alt="Screenshot 2024-09-13 at 3 57 53 PM" src="https://github.com/user-attachments/assets/cd489d69-bab4-4902-b41f-5695610ef90a">

**Comment by nanxiaobei** [comment]
can not reproduce on Safari 18.1
