### ISSUE TITLE
Version 4.23.0 not working with react 16.13.1

### ISSUE THREAD

**Issue by AlxZB-UI** [nanxiaobei/antd-img-crop#297]
Hi everyone, 

I have some trouble implement the latest version of andt-img-crop with my react project (version 16.13.1)  but I can't update it because is a large project and I'm use many libraries 

I hope you can help me with this or maybe can you guide me, I share the follow [example](https://codesandbox.io/p/sandbox/4f759l) for more details about the issue and the project config. Thanks

**Comment by wangdaners** [comment]
I also encountered the same issue

**Comment by nanxiaobei** [comment]
can not reproduce it with `react@16.13.1` in the minimal demo
