### ISSUE TITLE
antd的主题被覆盖了

### ISSUE THREAD

**Issue by yunwuxin** [nanxiaobei/antd-img-crop#37]
https://github.com/nanxiaobei/antd-img-crop/blob/282d6919fd5654f66597fc0dfd002d395ccf139d/src/index.jsx#L10

你这里直接引入了css文件  导致antd设置的主题 被你这个css覆盖掉了

**Comment by nanxiaobei** [comment]
后续会考虑不引入组件样式文件

**Comment by nanxiaobei** [comment]
`2.5.0` 版本中已移除 CSS 引入
