### ISSUE TITLE
is it possible to use this with Form.Item?

### ISSUE THREAD

**Issue by Dev142** [nanxiaobei/antd-img-crop#38]
I am trying to use it with antd form:
<Form.Item {...props} valuePropName="file" **getValueFromEvent={returnUploadedFileObject}**>
            <ImgCrop width='250' height='250' contain>
              <Upload
                listType="picture"
                showUploadList={false}
                onChange={handleChange}
                accept={props.accept}
              >
                <>
                  <Button>{loading ? <LoadingOutlined/> : ''} Browse</Button>
                </>
              </Upload>
            </ImgCrop>
          </Form.Item>

But I am not getting any event in **returnUploadedFileObject**. Is it possible to bind value with form?

**Comment by nanxiaobei** [comment]
It's `ImgCrop` component, not `Upload` component, two different components.
So you can't use it as `Upload` to emit `getValueFromEvent`.

If want to use in `Form.Item`, you need to wrap it to be a [**Customized Form Controls
**](https://ant.design/components/form/#components-form-demo-customized-form-controls)

**Comment by FatBuTa** [comment]
> It's `ImgCrop` component, not `Upload` component, two different components.
> So you can't use it as `Upload` to emit `getValueFromEvent`.
> 
> If want to use in `Form.Item`, you need to wrap it as a **[Customized Form Controls ](https://ant.design/components/form/#components-form-demo-customized-form-controls)**

@nanxiaobei I try to use with Form.Item but failed. Nothing happen after I upload a file

`const ImgCropCustomize: React.FC<ImageCropProps> = ({ value = {}, loading, data, imageUrl, onChange, beforeUpload }) => {
    return (
      <ImgCrop shape="round" zoom rotate grid modalTitle="Chỉnh sửa hình đại diện">
        <Upload
          action={`${BASE_URL}/common/upload-file`}
          headers={{}}
          defaultFileList={value.fileList}
          fileList={value.fileList}
          accept=".jpg,.png"
          data={data}
          showUploadList={false}
          multiple={false}
          name="filePost"
          listType="picture-card"
          beforeUpload={beforeUpload}
          onChange={onChange}
        >
          {imageUrl ? (
            <Avatar size={300} className={styles.avatar} src={imageUrl} alt="avatar" />
          ) : (
            <div>
              {loading ? <LoadingOutlined /> : <PlusOutlined />}
              <div className="ant-upload-text">Upload</div>
            </div>
          )}
        </Upload>
      </ImgCrop>
    );
  };

export default ImgCropCustomize;`

In this code I try to implement an Avatar for user profile.
Could you please help!
