### ISSUE TITLE
ie10裁剪框不能拖拽

### ISSUE THREAD

**Issue by gx191179173** [nanxiaobei/antd-img-crop#4]

**Comment by nanxiaobei** [comment]
你好，
暂未测试过在 IE10 下的使用。
不过 antd-img-crop 的拖拽裁切，是调用的 [react-image-crop](https://github.com/DominicTobias/react-image-crop) 库。
所以是否支持 IE10，需要依赖 `react-image-crop` 的支持情况，谢谢。
