### ISSUE TITLE
添加自定义okText和cancelText

### ISSUE THREAD

**Issue by KayShen** [nanxiaobei/antd-img-crop#40]
求在modal里添加自定义的okText和cancelText

**Comment by nanxiaobei** [comment]
已升级 `3.2.0`，添加了 `modelOk` 与 `modelCancel` 两个属性

**Comment by TonyZXY** [comment]
unable to add modelOk and modelCancel because of missing props interface

**Comment by nanxiaobei** [comment]
Thank you for your response, that was a mistake.
Please try the new `v3.3.0` version.

**Comment by TonyZXY** [comment]
感谢回应，已升级到 `v3.3.0`， 并且成功自定义 `modelOk` 与 `modelCancel`
