### ISSUE TITLE
ant-slider is not show

### ISSUE THREAD

**Issue by kamilml** [nanxiaobei/antd-img-crop#42]
Hello! and thanks for this awesome component ♥

I have this problem, the sliders is not show in the modal.

![Test Image 4](https://i.imgur.com/vVjybRr.png)

**Comment by nanxiaobei** [comment]
`antd-img-crop` does not import the style files of the components used inside, 
so if your project does not import the `Slider` component, 
you may need to import the component style file yourself:

```js
import 'antd/es/slider/style';
```
