### ISSUE TITLE
When cropping a file, the size increases exponentially.

### ISSUE THREAD

**Issue by DustTail** [nanxiaobei/antd-img-crop#43]
1. The size of the resulting file is many times larger than the original file size. this happens when loading jpeg files. 
2. The resulting file is always of image/png type.

On screenshots, I tried to crop a 10.2mb jpeg image, width 10315px, height 7049px.
Output is 117.1 mb png image, width 7049px, height 7049px;
![image](https://user-images.githubusercontent.com/52581427/83866045-da8a0000-a72f-11ea-814b-21c54b6eda67.png)
![image](https://user-images.githubusercontent.com/52581427/83866098-efff2a00-a72f-11ea-89c1-907c7936a387.png)

**Comment by nanxiaobei** [comment]
Please try the new `3.4.0` version, image size and type problem have been solved.
