### ISSUE TITLE
Modal doesn't display properly

### ISSUE THREAD

**Issue by balmacefa** [nanxiaobei/antd-img-crop#44]
I have this issue with the modal when I click the add button,
the modal doesn't display properly and is positioned in a corner of the screen:

![Modal](https://user-images.githubusercontent.com/8296124/83936231-eea91e00-a77e-11ea-8492-59195c730ccc.png)

I'm using:

"antd": "4.2.5"
"ant-design-pro": "4.0.0"

Not custom css.

**Comment by nanxiaobei** [comment]
`antd-img-crop` does not import the style files of the components used inside,
so if your project does not import the Modal component,
you may need to import the component style file yourself:

```js
import 'antd/es/modal/style';
```
