### ISSUE TITLE
Reopen the modal?

### ISSUE THREAD

**Issue by 340rahul** [nanxiaobei/antd-img-crop#45]
Is there a way to allow the user to reopen the modal for editing again?

**Comment by nanxiaobei** [comment]
What "reopen"?

**Comment by 340rahul** [comment]
Is there a way to open the modal again after the OK button has been clicked? For situations where I want to edit the image again?

**Comment by nanxiaobei** [comment]
Currently no way to do that, when clicked OK, the image will be upload to server immediately.

**Comment by tragicmj** [comment]
This feature should be there, like allowing to re crop images for next time instead of re uploading and cropping again.

**Comment by nanxiaobei** [comment]
"uploading" behavior is an `antd` original behavior, can not change it.

**Comment by tragicmj** [comment]
No, I meant using it as a separate component without antd upload component
