### ISSUE TITLE
Error: These dependencies were not found

### ISSUE THREAD

**Issue by zombieJ** [nanxiaobei/antd-img-crop#49]
antd web start failed: 

<img width="650" alt="截屏2020-06-15 下午8 47 51" src="https://user-images.githubusercontent.com/5378891/84659199-9ece1200-af49-11ea-90d2-264d1a3fdb87.png">

**Comment by nanxiaobei** [comment]
Did you use the latest version `3.6.0`?
Please make sure you have the `antd` package installed.
And you can paste your usage of `<ImgCrop>` code here.

**Comment by zombieJ** [comment]
clone https://github.com/ant-design/ant-design.git run `npm start` will get the error.

<img width="413" alt="截屏2020-06-15 下午10 10 51" src="https://user-images.githubusercontent.com/5378891/84667543-15bcd800-af55-11ea-9e68-989c858d02cc.png">

**Comment by nanxiaobei** [comment]
Please try the new `3.6.1` version.
Basically it's a strange module import case when using `bisheng`, which is the `ant-design` site static generator.
I don't get into it too much, I just used a "hack" to fix the error.

https://github.com/nanxiaobei/antd-img-crop/commit/ba337b5e293b2578aaf0124c5ea080977d8d428c#diff-73642d587163f2eb4d72f0fa6ebfba02
