### ISSUE TITLE
Importing 'antd-img-crop' overriding existing CSS.

### ISSUE THREAD

**Issue by tzgc** [nanxiaobei/antd-img-crop#5]
Hi,
Need help!  I am currently using the plugin and facing an issue, that whenever I import the plugin, It overrides my existing CSS. Any idea why this is happening?

Adding below line of code is creating the issue:
**"import ImgCrop from 'antd-img-crop';"**

Thanks.

**Comment by nanxiaobei** [comment]
Hi,
Can you provide a reproducible demo?
Need some more detailed specifics to see what happend, thanks.

**Comment by tzgc** [comment]
Hi,
Unfortunately, I don't have a 'codesandbox' demo for you to recreate the issue as it is specific to my environment. Just wondering that what CSS you are using and is there any way to disable it?

Thanks.

**Comment by nanxiaobei** [comment]
Sorry, I can't fix a 'problem' without 'seen' it.

**Comment by ahuynh-s** [comment]
Hello,
I am also having this problem. [Here](https://codesandbox.io/s/solitary-sound-5uxsq?fontsize=14&hidenavigation=1) is a code sandbox to reproduce the problem.
Thank you.

**Comment by nanxiaobei** [comment]
Hi, because `antd-img-crop` is rely on `antd`. styles changed because `antd-img-crop` imported `antd/lib/style/index.css`, the basic styles of `antd`.

Since you use `antd-img-crop`, you must use `antd`, you must use `Upload` component of `antd`, and this file is bound to imported.

**Comment by ahuynh-s** [comment]
Hi,
I am already using `antd` and have `antd/lib/style/index.css` imported. I am using custom css to override that css. When I use `antd-img-crop`, `antd/lib/style/index.css` gets imported an additional time and overwrites my css.
Thanks.

**Comment by nanxiaobei** [comment]
Please try version `2.4.0`, now `antd-img-crop` do not import `antd/lib/style/index.css` any more.
But the Modal of `antd-img-crop` uses the default CSS of `antd`, if you want to override them, you must add the custom CSS.
