### ISSUE TITLE
Uncaught (in promise) Error: Cannot find module 'antd/es/modal/style'     at dist lazy ^.*$ namespace object:26

### ISSUE THREAD

**Issue by antgodev** [nanxiaobei/antd-img-crop#50]
Uncaught (in promise) Error: Cannot find module 'antd/es/modal/style'
    at dist lazy ^.*$ namespace object:26
<img width="501" alt="WX20200617-130802@2x" src="https://user-images.githubusercontent.com/63995295/84857431-a30a4480-b09b-11ea-8feb-8395b1813baa.png">

**Comment by Haqverdi** [comment]
Same Error

**Comment by nanxiaobei** [comment]
Please try the new `3.8.0` verison.
