### ISSUE TITLE
在getFieldDecorator中使用ImgCrop的时候会报错，找不到refs，请问有什么解决方法吗？

### ISSUE THREAD

**Issue by huhaha24** [nanxiaobei/antd-img-crop#51]
**背景：**想在表单中使用antd4提供的Imgcrop上传并裁剪图片，使用后发现会报找不到refs，请问有办法解决吗？

* * *

**代码：**
```
{getFieldDecorator('logo')(
    <ImgCrop>
      <Upload
        action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
        listType="picture-card"
      >
        上传
      </Upload>
    </ImgCrop>
)}
```

* * *
**报错信息：**
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

**Comment by nanxiaobei** [comment]
使用在 `Form.Item` 中的时候，需要自行对 `ImgCrop` 进行自定义表单控件包装。

https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by huhaha24** [comment]
谢谢～

**Comment by nanxiaobei** [comment]
`forwardRef` 已添加，请尝试 `3.8.0` 版本。

**Comment by huhaha24** [comment]
好的
