### ISSUE TITLE
When used inside a form with other input elements it clears the data entered after image is uploaded (codesandbox attached).)

### ISSUE THREAD

**Issue by 340rahul** [nanxiaobei/antd-img-crop#53]
Hello, it's me again. When I use the image cropper inside a form which has other input fields the data, which is stored in the component's state, is cleared after I upload the image. Please check the codesandbox attached for a demo. First, enter the name and age, and then add an image using the cropper. You will see that the component's state is cleared after the image is uploaded.

https://codesandbox.io/s/beautiful-torvalds-frxpk?file=/src/App.js

**Comment by nanxiaobei** [comment]
Tried your demo and the input text is still there

**Comment by 340rahul** [comment]
I have updated the sandbox a little bit to try to make the issue more clear. When the app loads the form has two initial values name: initial name & age: 0. These are taken from the formData state of app. Now, before uploading the image, change the name and age values to something else. Then upload the image and press OK on crop modal. You will see that after the modal closes the input text is back to the initial values and the changes you made are gone.

**Comment by 340rahul** [comment]
I am printing the state below the form. While the values in the input don't change you will see that the state is reset.

**Comment by nanxiaobei** [comment]
Thanks for your feedback, It is a issue caused by React Hooks closure.
Please try the new `3.9.0` version.

**Comment by 340rahul** [comment]
Yep! That fixes it. It works now. Thanks!
