### ISSUE TITLE
black border on cropped image

### ISSUE THREAD

**Issue by trinityEon** [nanxiaobei/antd-img-crop#54]
Hi, Thank you for a great add-on to enable antd to be able to crop and rotate images.  

There are two issues that I have spotted. 

1. Currently when I upload an image without cropping or rotating, there is a thin black border on the left. (or left and top if you were to drag the image so that the top left corner is top left). This seems to only be happening with any jpg image with a predominantly white background that is 180px by 200px. (See screenshot attached of codepen example)
![Screenshot 2020-06-23 at 00 43 38](https://user-images.githubusercontent.com/1106670/85342338-a746bf80-b4ea-11ea-9e0e-68df351a84bf.png)

Sample image that easily replicates the black border when upload:
![APic2](https://user-images.githubusercontent.com/1106670/85343056-3bfded00-b4ec-11ea-8893-b705852d4809.jpg)

2. When rotating an image that is uploaded, the blank fillspace of the image is black. If I change the background color of the crop container, that can as per the react-easy-crop plugin discussion in the link below allow you to change the background color of the blank fillspace:

https://github.com/ricardo-ch/react-easy-crop/issues/148

see this demo: https://codesandbox.io/s/react-easy-crop-demo-with-cropped-output-m0spo?file=/src/styles.js

I was thinking of adding in a colorpicker ability for the user to be able to pick the background color fillspace or have this be done automatically. Perhaps it could be done where the zoom/crop slider is on the popup using something like this: https://github.com/casesandberg/react-color

Using antd-img-crop, How would I be able to change the background color of the fillspace? Would I need to pass in an extra prop?

I thank you in advance.

**Comment by nanxiaobei** [comment]
Thank you for letting me know this,
but sorry currently I have no time to add this feature, and PR welcome.
