### ISSUE TITLE
picture crop error in IOS

### ISSUE THREAD

**Issue by mani62** [nanxiaobei/antd-img-crop#55]
I have encountered a problem during upload a cropped picture.
When I upload a picture after I cropped it,The picture is displayed as a black photo in IOS.
How can I fix this problem?

**Comment by nanxiaobei** [comment]
Mobile is not tested and supported at present, since `antd` is a UI library for desktop.

**Comment by daoke0818** [comment]
IOS上裁剪后黑屏，哪位大神解决一下呢？
