### ISSUE TITLE
Allow only images

### ISSUE THREAD

**Issue by pragnyatata** [nanxiaobei/antd-img-crop#57]
When I upload a file like a pdf or a video the cropper doesn't display anything and If I click Ok now I get an error. I want to put restrictions on extensions allowed how to do it? How to handle this error.
[demo link](https://codesandbox.io/s/antd-img-crop-u0wkv?file=/src/index.js)

**Comment by nanxiaobei** [comment]
Use `accept` prop of `antd` `Upload` to customize the accept file types.

https://ant.design/components/upload/#API
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept
