### ISSUE TITLE
剪裁后的图片特别模糊，请问要如何解决？

### ISSUE THREAD

**Issue by doveq** [nanxiaobei/antd-img-crop#60]
剪裁后的图片特别模糊，100KB的图片剪裁后只有20KB（尺寸没变），请问要如何解决？

**Comment by doveq** [comment]
网上有类似的问题和解决方案
https://www.jianshu.com/p/3c223211ca7e

**Comment by nanxiaobei** [comment]
可 fork 后修改此行传的参数，
图片大小，0 最小 ，1 最大（对应图片质量高），目前为 0.4
https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L253
