### ISSUE TITLE
缩放和旋转的拖动条消失了

### ISSUE THREAD

**Issue by edifangyi** [nanxiaobei/antd-img-crop#61]
![image](https://user-images.githubusercontent.com/12421552/89202853-2a792c00-d5e6-11ea-9a14-2162d0a5dd29.png)

![image](https://user-images.githubusercontent.com/12421552/89202638-d706de00-d5e5-11ea-9bf3-9a4ea5af1473.png)

ant-slider-mark 的style消失了

antdpro 最新版，chrome，官方Demo有拖动条，我的消失了。

**Comment by nanxiaobei** [comment]
需自行引入样式文件：

```js
import 'antd/es/modal/style';
import 'antd/es/slider/style';
```
