### ISSUE TITLE
Firefox Developer version Issue

### ISSUE THREAD

**Issue by danialdezfouli** [nanxiaobei/antd-img-crop#63]
Resizing is not working correctly in Firefox even though it's ok with Chrome.

"antd": "^4.4.2",
"antd-img-crop": "^3.9.0",

**Comment by Julienblc** [comment]
Same for me.
Firefox 79.0
"antd": "^4.3.5",
"antd-img-crop": "^3.9.0"

**Comment by nanxiaobei** [comment]
Sorry, but now I don't have more time to deal with different browsers, and PR welcome.
