### ISSUE TITLE
feature request: expose more props from react-easy-crop (minZoom, maxZoom, restrictPosition, etc.)

### ISSUE THREAD

**Issue by matulef** [nanxiaobei/antd-img-crop#67]
React-easy-crop provides several more props that could be exposed by antd-image-crop. In particular, for my use case, I'd like to be able to set the minZoom parameter to something less than 1 (sometime it's useful to allow the user to shrink an image to fit within a given aspect ratio).  React-easy-crop has a prop for this, it just needs to be passed in.

**Comment by nanxiaobei** [comment]
Sorry but the design concept of `antd-img-crop` is as simple as possible, do not want to add too many props.
You can fork or copy the code and enhance it yourself.

**Comment by matulef** [comment]
I understand. I agree that too many props can be overwhelming. However, there's really just one prop that I care about: minZoom. Right now, if your image is square but you need to crop it to fit inside a rectangle, your only option is to cut off the top and bottom of the square, rather than leaving empty space on the sides. Setting minZoom to something less than 1 (e.g. 0.5) should solve this. This seems like a common use case, so I think it's worth considering. 

In any case, thanks for maintaining this library! When I have time I'll fork it and experiment.
