### ISSUE TITLE
Add more feature (resize cropper)

### ISSUE THREAD

**Issue by hmz22** [nanxiaobei/antd-img-crop#68]
Hi Dear,
For now this component just have zoom and can't resize crop box please add resize crop box with aspect ratio.

**Comment by nanxiaobei** [comment]
`antd-img-crop` is rely on [`react-easy-crop`](https://ricardo-ch.github.io/react-easy-crop/), only the picture can be zoomed in and out.

At present, the function of resizing the crop box will not be realized.
