### ISSUE TITLE
Cropper Size issue

### ISSUE THREAD

**Issue by dbuddhadev13** [nanxiaobei/antd-img-crop#69]
Cropper size is inconsistent. Default width should be set to be 100% of the image width.
Cropper width does change to 100% once we rotate the image even by 1 degree.

![image](https://user-images.githubusercontent.com/63302297/90613343-dba6d580-e226-11ea-9d59-0e1c979b4e3d.png)

**Comment by nanxiaobei** [comment]
This situation cannot be reproduced, please provide some more detailed instructions.

**Comment by dbuddhadev13** [comment]
![Ganpati Pudi](https://user-images.githubusercontent.com/63302297/90615014-1ad62600-e229-11ea-8765-9e07cec1b6fa.jpg)

When I try to upload the attached image on the demo, the crop area is defaulted to a small square as shown in my original message. When i rotate the image a little, the crop area changes width to fit the image as shown below. 

![image](https://user-images.githubusercontent.com/63302297/90615863-4c032600-e22a-11ea-84a7-bdc0a3521e59.png)

**Comment by nanxiaobei** [comment]
I can't reproduce the "small square" crop area, it's full width crop area.
![uSqjf.png](https://s3.jpg.cm/2020/08/19/uSqjf.png)

**Comment by tankadesign** [comment]
This is exactly the same issue I came across in Safari 13.1.2 on desktop.

**Comment by ZSergan** [comment]
I have the same issue in Firefox 79.0
![Screen Shot 2020-08-25 at 6 18 37 PM](https://user-images.githubusercontent.com/56780779/91150751-24b3c980-e700-11ea-9d4e-a032f498c06b.png)

**Comment by nanxiaobei** [comment]
Sorry, but now I don't have much time to deal with different browsers, only tested Chrome.
PR welcome.

**Comment by diogobiz** [comment]
this problem still exists I testing on the antd example (https://4x.ant.design/components/upload/)
