### ISSUE TITLE
嵌套在Form中使用getFieldDecorator无法接收Upload onChange事件

### ISSUE THREAD

**Issue by liangbx361** [nanxiaobei/antd-img-crop#7]
getValueFromEvent设置的事件不回调

{getFieldDecorator('icon', {
                            rules: [
                                {
                                    required: true,
                                }
                            ],
                            initialValue: icon,
                            valuePropName: 'file',
                            getValueFromEvent: this.iconUploadListener
                        })(
                            <ImgCrop>
                                <Upload
                                    name="imageFile"
                                    action="/v1/image"
                                    listType="picture-card"
                                    showUploadList={false}
                                >
                                    {icon ? <img src={icon.url} alt="icon" /> : uploadButton}
                                </Upload>
                            </ImgCrop>
                        )}

**Comment by nanxiaobei** [comment]
你好，使用 `getFieldDecorator` 包裹的前提，组件需为[自定义表单控件](https://ant.design/components/form-cn/#components-form-demo-customized-form-controls)，目前，`antd-img-crop` 并不是自定义表单控件，建议根据 `antd-img-crop` 源代码自行改造一下。
