### ISSUE TITLE
不兼容IE 有解决方案吗？

### ISSUE THREAD

**Issue by Tmargin** [nanxiaobei/antd-img-crop#74]

**Comment by nanxiaobei** [comment]
你好，具体报错信息是？

**Comment by Tmargin** [comment]
Unhandled promise rejection TypeError: Object doesn't support property or method 'toBlob'





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "南小北"<notifications@github.com&gt;; 
发送时间: 2020年9月4日(星期五) 下午2:47
收件人: "nanxiaobei/antd-img-crop"<antd-img-crop@noreply.github.com&gt;; 
抄送: "____"<1010161292@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nanxiaobei/antd-img-crop] 不兼容IE 有解决方案吗？ (#74)





 
你好，具体报错信息是？

**Comment by nanxiaobei** [comment]
可引入此 polyfill 解决
https://github.com/blueimp/JavaScript-Canvas-to-Blob
