### ISSUE TITLE
想问下能不能添加一个跳过裁切的API

### ISSUE THREAD

**Issue by David2k13** [nanxiaobei/antd-img-crop#75]
现在就是有一个需求gif文件格式不进行裁切，现在也没找到比较好的解决方案，想问下能不能添加一个跳过裁切的API

**Comment by nanxiaobei** [comment]
你好，可自行在项目中修改 `antd-img-crop` 使用，暂不准备将此功能加入。

**Comment by careteenL** [comment]
如果有类似需求的同学可以使用[@careteen/antd-img-crop](https://www.npmjs.com/package/@careteen/antd-img-crop)代码可参考[gifCrop示例/默认gif跳过裁剪](https://github.com/careteenL/antd-img-crop/blob/master/examples/basic/src/App.js#L40-L79)
> 与此同时特别感谢 @nanxiaobei

**Comment by David2k13** [comment]
> 如果有类似需求的同学可以使用[@careteen/antd-img-crop](https://www.npmjs.com/package/@careteen/antd-img-crop)代码可参考[gifCrop示例/默认gif跳过裁剪](https://github.com/careteenL/antd-img-crop/blob/master/examples/basic/src/App.js#L40-L79)
> 
> > 与此同时特别感谢 @nanxiaobei

谢谢，你这个是我这个修改版的早期版本的fork，我优化了代码https://github.com/David2k13/antd-img-crop-cw

**Comment by M1seRy** [comment]
fork 了一个版本，不支持裁剪的图片不弹窗但会 resolve file  => https://www.npmjs.com/package/antd-img-cropper
```js
        beforeUpload: (file, fileList) => {
          return new Promise(async (resolve, reject) => {
            if (beforeCrop && !(await beforeCrop(file, fileList))) {
              // reject();
              return resolve(file);
            }
```

**Comment by dx-pioneer** [comment]
为啥beforeCrop这个函数return file在不同环境下表现不一致
