### ISSUE TITLE
为什么裁剪的都是图片右上角部分，而且宽高不是设定的宽高，看demo也是这样

### ISSUE THREAD

**Issue by dandandexia** [nanxiaobei/antd-img-crop#8]
为什么裁剪的都是图片右上角部分，而且宽高不是设定的宽高，看demo也是这样

**Comment by nanxiaobei** [comment]
你好，感谢反馈。
经确认，当图片宽度大于弹框宽度时会存在问题，已在 1.0.1 版本中修复。
请升级 1.0.1 版本使用~
