### ISSUE TITLE
IE浏览器编辑图片后浏览器报错

### ISSUE THREAD

**Issue by lijiemoop** [nanxiaobei/antd-img-crop#80]
浏览器版本： **ie11**
问题描述： 编辑图片后点击“确定”按钮后出错，浏览器报错
报错信息： **SCRIPT438: 对象不支持“remove”属性或方法**

**Comment by nanxiaobei** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/ChildNode/remove#Polyfill
试试这个

**Comment by lijiemoop** [comment]
> https://developer.mozilla.org/zh-CN/docs/Web/API/ChildNode/remove#Polyfill
> 试试这个

是的，这个在源码上修改可以解决这个问题，需要在引入的_react-easy-crop_包里进行修改，所以才提了这个issue

**Comment by nanxiaobei** [comment]
谢谢~ 暂不考虑对 IE 支持做兼容处理。

**Comment by lijiemoop** [comment]
问题已解决
