### ISSUE TITLE
剪切后图片失真严重。

### ISSUE THREAD

**Issue by leedorian** [nanxiaobei/antd-img-crop#83]
剪切后图片失真严重。

**Comment by nanxiaobei** [comment]
目前可自行调整本行图片质量参数：https://github.com/nanxiaobei/antd-img-crop/blob/master/src/index.jsx#L265
后续会增加 props 进行外部控制

**Comment by leedorian** [comment]
👍

**Comment by nanxiaobei** [comment]
`3.13.0` 已添加 [`quality `](https://github.com/nanxiaobei/antd-img-crop/blob/master/README.zh-CN.md#props) 属性
