### ISSUE TITLE
Error: DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D':

### ISSUE THREAD

**Issue by careteenL** [nanxiaobei/antd-img-crop#89]
**您好，很感谢您提供的`antd-img-crop`组件**

当我在配合`antd`使用时，有遇到一个问题：

上传一个实际为`word`类型，但将后缀名改为`png`的文件时，

控制台有报错`DOMException: Failed to execute 'getImageData' on 'CanvasRenderingContext2D':`

但是界面没有任何反馈，

**期望为其添加一个`onError`的`props`**

**Comment by nanxiaobei** [comment]
暂不准备添加此功能，感谢~

**Comment by careteenL** [comment]
如果有类似需求的同学可以使用[@careteen/antd-img-crop](https://www.npmjs.com/package/@careteen/antd-img-crop)代码可参考[onError示例](https://github.com/careteenL/antd-img-crop/blob/master/examples/basic/src/App.js#L80-L83)
> 与此同时特别感谢 @nanxiaobei
