### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by Jackie-Web** [nanxiaobei/antd-img-crop#9]
我用到了你的插件，我发现你这边打包时 打包方式好像是错了。我引用后会报错误。
![image](https://user-images.githubusercontent.com/11611057/57966583-968e5680-7986-11e9-80c5-ffc3d8d5059c.png)
![image](https://user-images.githubusercontent.com/11611057/57966587-9ee69180-7986-11e9-9dcc-325fb025e0ad.png)
可以在打包的时候 把 import 也一起打包了吗？ 谢谢啦

**Comment by nanxiaobei** [comment]
你好，我在使用中暂未遇到此问题。麻烦提供一个可复现的 demo，谢谢。
