### ISSUE TITLE
Allow Modal to have modalProps spread for more control

### ISSUE THREAD

**Issue by jwmann** [nanxiaobei/antd-img-crop#95]
I would like the ability to pass the `confirmLoading` prop or add a spinner to the "Ok" button.

This is to allow the user some visual feedback that the computer is doing something.
Depending on the size of the photo, this may take a moment.

Having a prop called `modalProps` would give more flexibility to expand some of the Ant Design Modal Props.

**Comment by nanxiaobei** [comment]
PR welcome.

**Comment by nanxiaobei** [comment]
Supported in `4.9.0`.
