### ISSUE TITLE
Fill color does not always extend to full canvas area

### ISSUE THREAD

**Issue by hablodoug** [nanxiaobei/antd-img-crop#97]
![image](https://user-images.githubusercontent.com/66522737/98943337-3cbd0d00-24e7-11eb-8296-72d527a81aef.png)

Using the default white background colour for example, when images are zoomed out too much, the white fill colour ends and black bars appear at the edge of the image.

**Comment by hablodoug** [comment]
Actually... Even at zoom=1, if `restrictPosition` is set to `false` in the `cropperProps`, then if the image is moved a fair bit beyond the canvas area, the white background doesn't cover the whole background.

![image](https://user-images.githubusercontent.com/66522737/98944752-6ecf6e80-24e9-11eb-8202-a74166bfb164.png)
![image](https://user-images.githubusercontent.com/66522737/98944933-ba821800-24e9-11eb-84ca-915b243ac06e.png)

**Comment by hablodoug** [comment]
Perhaps need to make the canvas bigger, to account for both the image being moved to the edge of the canvas, and also taking into account the zoomVal? 

Not sure how to edit the library to check for myself, but thinking it might be...

```
    const maxWidth = (naturalWidth * 2) / zoomVal;
    const maxHeight = (naturalHeight * 2) / zoomVal;
    canvas.width = maxWidth;
    canvas.height = maxHeight;
```

and replace wherever `maxLen` appears with `maxWidth` or `maxHeight`

**Comment by nanxiaobei** [comment]
The original intention of creating this library is a very simple function: cutting a big image into a small image.

But things have changed, and PR has been coming, for example, `cropperProps`, this is not what I expected.

I don't have time and energy to deal with this kind of edge case for now.

I think this case is just imperfect, and not a bug. So I'm sorry, it won't be improved right now.

If someone can provide a PR, I will be very welcome.
