### ISSUE TITLE
cropperProps overwritten by onZoomChange function

### ISSUE THREAD

**Issue by hablodoug** [nanxiaobei/antd-img-crop#99]
Not possible to set own custom onZoomChange function, i.e. can't get the current zoom value outside of the component

![image](https://user-images.githubusercontent.com/66522737/99182294-150ab680-272c-11eb-9623-91ba01dc87cb.png)

**Comment by hablodoug** [comment]
So, for example, it's not possible to get anything like this working:

```
<ImgCrop
cropperProps={{
          restrictPosition: restrictPosition,
          onZoomChange: (level) => setRestrictPosition(level < 1)
        }}
```

**Comment by nanxiaobei** [comment]
Not a bug, PR welcome.
